navidrome/navidrome

Makefile
which failed because a 'go get' command was given as an argument to
'go get'
=> Fix dependency installation using Makefile

db/migration/20200325185135_add_album_artist_id.go, model/album.go, model/mediafile.go, persistence/album_repository.go, persistence/artist_repository.go, persistence/artist_repository_test.go, persistence/helpers.go, persistence/helpers_test.go, persistence/mock_album_repo.go, persistence/persistence_suite_test.go, persistence/playlist_repository_test.go, scanner/tag_scanner.go, ui/src/album/AlbumList.js, ui/src/artist/ArtistList.js
This change introduces an Artist filter in the album view. Compilations that have any tracks by the artist will also be displayed
Fixes #94
=> Fix Artist filter

conf/configuration.go, server/app/serve_index.go, server/app/serve_index_test.go, ui/src/authProvider.js, ui/src/config.js, ui/src/layout/Login.js, ui/src/utils/baseUrl.js
This PR enables configuring the image used in the login background. 
By default, the login shows a random, music related, image from Unsplash.com. With this new configuration, you can set a different image URL to be used as the background. Ex:
```
ND_UILOGINBACKGROUNDURL=https://images.hdqwalls.com/download/5k-colorful-galaxy-ko-1920x1080.jpg
```
You can even set it to a embedded image, with no external lookups. Ex of a black background:
```
ND_UILOGINBACKGROUNDURL=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAAABGdBTUEAALGPC/xhBQAAAiJJREFUeF7t0IEAAAAAw6D5Ux/khVBhwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB …
```
=> Make Login background configurable

engine/media_streamer.go, engine/media_streamer_test.go, engine/transcoder/ffmpeg.go, engine/transcoder/ffmpeg_test.go
- Remove the useless "format" parameter
- createTranscodeCommand now returns a list of string, instead of (string, string[])
=> Simplify a bit ffmpeg's transcoder

conf/configuration.go, scanner/metadata_ffmpeg.go, scanner/metadata_test.go
- createProbeCommand returns a []string instead of (string, string[])
- Simplify the loop of createProbeCommand
=> Refactor a bit how ffmpeg is used to get metadata

consts/consts.go, server/server.go
Configuration for ThrottleBacklog middleware. This would reduce server load and memory consumption. Server will process X requests parallel, X is between 2 and max amount of CPUs. 100 Requests will be hold in the queue.
Fixes #184
=> configuration for request throttling

.github/workflows/pipeline.yml
This PR skips the Docker build/push step, as it was always breaking for contributed PRs
Reason is that secrets are not available for PRs coming from a fork: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow
As there's no way to [check if secrets are available at the job level](https://github.community/t5/GitHub-Actions/How-can-I-test-if-secrets-are-available-in-an-action/td-p/50881), I added the check at each step of the docker job
=> Don't run Docker job in contributed PRs

db/migration/20200508093059_add_artist_song_count.go, model/artist.go, persistence/artist_repository.go, ui/src/artist/ArtistList.js, ui/src/i18n/en.json
Closes #234 
This change introduces a new term to be translated: `resources.artist.fields.songCount`
=> Add `songCount` column to Artist table

contrib/navidrome.service
This section apparently is mandatory now.
`multi-user` is a standard target that won't hurt anyone.
=> Add [Install] section to systemd unit file.

server/subsonic/album_lists.go
`getSongsByGenre` was returning data within the `randomSongs` element. Here's a sample of the XML response from my server:
```
<subsonic-response status="ok" version="1.10.2" type="navidrome" serverVersion="dev">
<randomSongs>
...
</randomSongs>
</subsonic-response>
```
This PR corrects the response so it's properly within a `songsByGenre` element.
=> Correct response body for getSongsByGenre

.github/workflows/pipeline.dockerfile, .goreleaser.yml
Latest AMD64 Linux builds are static, so there's no need to generate a binary specifically for MUSL.
Running in the latest Alpine images:
```
/lib/ld-musl-x86_64.so.1: ./navidrome: Not a valid dynamic program
#
_   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
Version: v0.24.0-SNAPSHOT (1bb11bd)
Navidrome is a self-hosted music server and streamer.
Complete documentation is available at https://www.navidrome.org/docs
Usage:
navidrome [flags]
```
@jvoisin Can you confirm the Linux AMD64 from the [binaries archive](https://github.com/deluan/navidrome/suites/897329280/artifacts/107 …
=> Remove MUSL build

persistence/mediafile_repository.go, persistence/mediafile_repository_test.go
This fix an issue where the scanner would end up with empty albums if any filepath starts with the album's path. Ex:
Contents of Music Folder:
```
/music/Ella Fitzgerald/1.mp3
/music/Ella Fitzgerald/2.mp3
/music/Ella Fitzgerald & Louis Armstrong - 3.mp3
/music/Ella Fitzgerald & Louis Armstrong - 4.mp3
```
This would cause the album composed by files 3 and 4 to be empty. The songs would be deleted from the DB because of the overlapping path.
=> ByPath queries should not match overlapping paths

ui/src/common/DurationField.js
This is a small fix to properly display a playlists length when it would go above 24 hours in length.
Previously, the length of the playlist shown would be the modulo over 24 hours, so a playlist of 26 hours would display as 02:00:00. With this fix it will display as 26:00:00.
=> Fixed playlist duration formatter to properly count lengths longer than 24 hours

ui/src/common/useAlbumsPerPage.js
Currently, `getPerPage()` for a width of 'md' will return `15` as the default `perPage` value, but offer the choices of 12, 24, 48 for "Items per page." This resolves that issue.
=> Fix default getPerPage for 'md' widths

core/artwork.go, ui/src/album/AlbumDetails.js, ui/src/album/AlbumGridView.js
If you have non-square album art for an album (maybe you ripped music from a DVD and have a DVD-sized cover, or maybe you just [enjoy the Cat Face theme song](https://www.youtube.com/watch?v=WlDiUQy-C64) more than you should and you grabbed a YouTube thumbnail for the cover art), then Navidrome messes up the aspect ratio.  This PR changes the album grid from this:
To this:
(Also, this is my very first commit to a golang project, and I don't actually know any golang, so apologies if there was a much easier way to do this.  :)
=> Fix aspect ratio for non-square album art.

core/cache/file_caches.go
Fixes #655.
Size is 0 anyway, so there's no point displaying it.
=> Fix startup failure when image cache is disabled.

ui/src/audioplayer/Player.js
This adjusts the AudioTitle component in the Player to:
- Show info on 2 lines, bolding the song title
- Show album
The second line is hidden on small screens when the player swaps to its mobile view.
=> Adjust AudioTitle in Player

persistence/mediafile_repository.go, persistence/mediafile_repository_test.go, ui/src/album/AlbumShow.js
If files cannot be sorted according to the query, fall back to ascending/descending file names.
One use case is a loose compilation of files with same album, album artist, and no track numbers. File order was then undetermined, in practice depended on insertion order in the database.
=> Fall back to artist and title after track id when sorting in albums

ui/src/i18n/en.json, ui/src/personal/Personal.js
This fixes the Notification preference switch being enabled but nonfunctional when the UI was not accessed in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). It will now be disabled and show the proper message.
=> Check for window.isSecureContext when determining Notification support

ui/src/dialogs/AboutDialog.js
Referring to the issue:- https://github.com/navidrome/navidrome/issues/815
=> Make the version number in the about dialog clickable

contrib/freebsd_rc
This is the same startup script used by the FreeBSD port multimedia/navidrome that I am working on (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254286).  Might be helpful for anyone that doesn't want to use the port.  Feel free to use a different filename if this one doesn't fit well.
=> Create rc.d startup script for FreeBSD

ui/src/album/AlbumDetails.js
@deluan, I tried to reproduce issue #647 but could not reproduce the same for the Albums; however, I found a similar issue of the horizontal scroll on AlbumDetail, and have done a few edits in the min-width of AlbumDetails.js.
Screenshot of the error page:
Page after the fix:
Please feel free to provide feedback.
Thank you!
=> Fix min-width in AlbumDetails

Makefile
as of now makefile shows a message
```Download go dependencies```
which can be changed to
```downloading go dependencies```
=> improved makefile message to developer

ui/src/authProvider.js
This fixes https://github.com/navidrome/navidrome/issues/613 by clearing the ServiceWorker cache on logout. Based on this code: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/keys . Seems to work on macOS and iOS, but please test on other platforms.
=> clear the ServiceWorker cache on logout

ui/src/dialogs/AboutDialog.js, ui/src/dialogs/AboutDialog.test.js
Referring to https://github.com/navidrome/navidrome/issues/815
=> Make the version number clickable for the SNAPSHOT version in development docker build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This adds 2 issue templates; one for bug reports and another one for feature requests.
After #831 is merged, I can also then remove the redundant issue template mentioned in the contributing docs and link to the issue template instead.
=> feat(github): add issue templates

ui/src/playlist/PlaylistSongBulkActions.js, ui/src/playlist/PlaylistSongs.js
#896 Bug Fixed :
`BulkDeleteButton` call `unselectAll` function which dispatch action to list reducer and unselect all selected ids from state, but list state of resource 'playlistTrack' have nothing in it because  `<List>`  or  `<ListBase>` components are not used.  I have fixed the bug by passing `onUnselectItems` function in `onClick`  prop of `BulkDeleteButton`.
Requesting review 
@deluan  @jvoisin
=> playlist bulkActionsToolbar bug

conf/configuration.go, server/app/serve_index.go, server/app/serve_index_test.go, ui/src/album/AlbumDetails.js, ui/src/album/AlbumList.js, ui/src/album/AlbumListView.js, ui/src/album/AlbumSongs.js, ui/src/album/albumLists.js, ui/src/artist/ArtistList.js, ui/src/audioplayer/PlayerToolbar.js, ui/src/common/ContextMenus.js, ui/src/common/SongContextMenu.js, ui/src/config.js, ui/src/hotkeys.js, ui/src/song/SongList.js
- Enabled feature to turn on/off the Favorites/Loved feature in the UI.
*It can also be seen that with Favorites being disabled the Favourites tab in the left SideMenu also gets disabled, and gets enabled automatically when the  Favorites feature is enabled again (refer last screenshot).*
=> Enabled feature to turn on/off Favorites/Loved feature. 

ui/src/authProvider.js
Closes #901 
- The cache storage is not available to chromium based browsers in Android
- so throws up error when trying to delete it (the error happens only for chromium based browsers in android)
- added a check to see if cache is available before trying to delete it
Related to #906
=> fix(authProvider.js) fix cacheUndefined bug - #901

ui/src/album/AlbumGridView.js
Closes #921 
Prevented link from wrapping over both the artistLinkField andRangeField.
The artistLinkField already has link inside, so wrapping another link tag over it caused the error.
=> fix(AlbumGrid): fix LinkWrapping Error #921

ui/src/layout/Login.js, ui/src/themes/dark.js
Extension from https://github.com/navidrome/navidrome/issues/927
Had to make a few changes to the dark theme so that it looks good.
Also, code changes are few, running prettier makes the diff go crazy :)
=> [Theme] Allow customizing Login Page

ui/src/config.js
~~Fixes~~ Relates to https://github.com/navidrome/navidrome/issues/928, unrelated background images
Fetches random photos from a defined collection instead of searching for keywords, which turns out to be somewhat inacurrate.
I've used the Music Wallpapers collection in this case - https://unsplash.com/collections/1065384/music-wallpapers, we can easily incorporate any other collection.
=> Login backgrounds from unsplash collection

ui/src/album/AlbumListView.js
Closes #925 
This was the initial error message shown
```
Warning: React does not recognize the `syncWithLocation` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `syncwithlocation` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in table (created by ForwardRef(Table))
in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
in WithStyles(ForwardRef(Table)) (created by ForwardRef)
in ForwardRef (at AlbumListView.js:78)
in AlbumListView (at AlbumList.js:96)
in div (created by ForwardRef(Paper))
in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
in ForwardRef(Card) (created by …
```
=> fix(albumListView)  prop undefined bug  #925

ui/public/navidrome-service-worker.js, ui/public/offline.html, ui/src/serviceWorker.js
This PR gives the Navidrome web UI a 'proper' own service worker, not just the current boilerplate `service-worker.js` that gets auto-generated during the build process by CRA, which is outdated anyway since it loads Workbox v3 libraries instead of the current v6.1.2. Plus, that service worker caches stuff for offline usage, which breaks things.
Workbox, by the way, is pretty cool stuff: basically it's a set of Google libraries to make service workers easy. See: https://developers.google.com/web/tools/workbox
Changes in this PR:
- updated serviceWorker.js to load this new service worker
- named the new service worker `navidrome-service-worker.js` so it doesn't get overwritten by the CRA generated one
- added a new file `offline.html` containing an error message
So what does the service …
=> New service worker

ui/src/album/AlbumListView.js, ui/src/common/SongDetails.js
Currently, when previewing the album details, the following error is seen in the console.
```Received `true` for a non-boolean attribute `multiline`.
If you want to write it to the DOM, pass a string instead: multiline="true" or multiline={value.toString()}.
in span (created by ForwardRef(Typography))
in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
in WithStyles(ForwardRef(Typography)) (at MultiLineTextField.js:25)
in Unknown
in Unknown (at SongDetails.js:35)
in td (created by ForwardRef(TableCell))
in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
in WithStyles(ForwardRef(TableCell)) (at SongDetails.js:63)
in tr (created by ForwardRef(TableRow))
in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
in …
```
=> Fix extra multiline Prop error

ui/src/user/UserEdit.js
Currrently selecting a user and  going to the UserEdit page, shows a warning in the console.
> Warning: Failed prop type: Invalid prop `variant` of value `outlined` supplied to `ForwardRef(Typography)`, expected one of ["h1","h2","h3","h4","h5","h6","subtitle1","subtitle2","body1","body2","caption","button","overline","srOnly","inherit"].
>     in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
>     in WithStyles(ForwardRef(Typography))
>     in Unknown
>     in Unknown (at UserEdit.js:47)
>     in div (created by Labeled)
>     in div (created by ForwardRef(FormControl))
>     in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
>     in WithStyles(ForwardRef(FormControl)) (created by Labeled)
>     in Labeled (created by FormInput)
>     in …
=> Fix 'undefined variant prop' in DateField warning

scanner/metadata/taglib.go, scanner/walk_dir_tree.go, scanner/walk_dir_tree_test.go
First off - thanks for `navidrome`!  It is so excellent - fast, easy on the eyes, and very straightforward to use and deploy.  The code is a pleasure to peruse.  
I use directory/ACL permissions to handle which folders I wish to allow media servers to access.
I noticed that upon hitting the first subdir without permission, navidrome would just abandon scanning entirely:
```
ERRO[0004] Error reading dir                             error="lstat /tank/whorfin/Audio/Synth: permission denied" path=/tank/whorfin/Audio
ERRO[0004] Error loading directory tree                  error="lstat /tank/whorfin/Audio/Synth: permission denied"
ERRO[0004] There were errors reading directories from filesystem  error="lstat /tank/whorfin/Audio/Synth: permission denied"
ERRO[0004] Scan was interrupted by …
```
=> Handle subdirectories without rx permission and allow ogg files w/o metadata

ui/src/themes/spotify.js
- https://github.com/navidrome/navidrome/pull/953 added some improvements to the login window. Ensure that spotify-ish doesn't override the good parts
- Possibly Fix https://github.com/navidrome/navidrome/issues/1072 (can't reproduce)
**Screenshot**
=> [Spotify-ish] Login consistent with other themes

contrib/navidrome.service
Applied suggestions from `systemd-analyze` and also using StateDirectory to ensure /var/lib/navidrome exists and is writeable
During my tests the option MemoryDenyWriteExecute didn't prevent ffmpeg from working, but according to this commit a18093e255433832ed5a0faca392ee872cafc5a2 it should, so I left it as it might cause problem on other distros.
=> Improve systemd unit security

conf/configuration.go, server/app/serve_index.go, server/app/serve_index_test.go, ui/src/config.js
This PR adds a `devEnableShare` flag for the in-progress share functionality. 
Follow-up to https://github.com/navidrome/navidrome/pull/930#issuecomment-850841845
=> Add devEnableShare config option

utils/request_helpers.go, utils/request_helpers_test.go
This will allow boolean query parameters to parse as true for the value `True` (for compatibility with Python)
=> Parse ParamBool case-insensitively

conf/configuration.go, log/log.go, log/redactrus.go, log/redactrus_test.go, server/app/auth.go, server/app/auth_test.go, server/app/serve_index.go, ui/src/authProvider.js
This is an attempt to address an issue described in #176 . Basically it allows auto-login user using forwarding proxy manager like authelia or vouch. This PR introduces two new config options:
* `ReverseProxyUserHeader` - HTTP header containing user name from authenticated proxy. Default: `Remote-User`
* `ReverseProxyWhitelist` - Coma separated lists of IP CIDRs which are allowed to use this feature - usually should contain reverse proxy IP with mask. Setting this to `0.0.0.0/0` would allow any connection to use the header (which is discouraged). By default everything is blacklisted, which means, this config parameter must be set to actually use the feature.
=> feat(auth): reverse proxy authentication support - #176

conf/configuration.go, consts/consts.go, db/migration/20210616150710_encrypt_all_passwords.go, log/log.go, model/user.go, persistence/user_repository.go, persistence/user_repository_test.go, server/auth.go, server/subsonic/middlewares.go, tests/mock_user_repo.go, utils/encrypt.go, utils/encrypt_test.go
This PR mitigates the issue with passwords in clear text (#202). As noted in the issue, to support Subsonic API's token authentication, we are forced to keep the passwords in a reversible format in the DB. 
By default, it encrypts the passwords with a shared encryption key, just for the sake of obfuscation as this key can be easily found in the codebase.
This key can be overridden by the new config option `PasswordEncryptionKey`. Once this option is set and Navidrome is restarted, it will re-encrypt all passwords with this new key. This is a one-time only thing, and after this point the config option cannot be changed anymore or users won't be able to authenticate. 
The idea for this implementation is that if the DB is compromised by SQL Injection, the key to decrypt is not part of the …
=> Encrypt passwords in DB

persistence/user_repository.go
After #1187, if you try to change your own password you get a "Password does not match" error. This is because the user is entering their current password in plain text, but it is being compared against an encrypted version of the password stored in the database.
This change fixes this issue by decrypting the password stored in the database and comparing it against the plaintext version provided by the user.
=> Addresses a bug that would prevent users from changing their own passwords, introduced as part of #1187.

ui/src/audioplayer/AudioTitle.js, ui/src/audioplayer/styles.js
Modifies the mobile and desktop players to add missing basic song info and create a more uniform look. The changes are (obviously) aligned with my preferences and may not fit the project's vision.  I figured I'd at least put them out here as a point of discussion.
- Hides the original artist field and adds a new artist field with style matching song title.
- Adds album and song year (if present) to player under artist field, with matching style.
- `EnableCoverAnimation` is now applied to the mobile player. When animations are disabled, the cover is displayed square with a width up to 85%. For large mobile screens (e.g. iPad) the maximum width is capped at 600 px. Closes #1265.
- Song year is added to song info when present in the format of "Artist - Album - Year".
=> Add missing song information to players and apply EnableCoverAnimation to mobile player.

.github/workflows/pipeline.yml, Makefile
Do away with `.gitinfo` file and just do some path string transformations.  We won't know the git hash, but we will get the version correct.
Potential fix for #1302
=> Extract version from directory name if .git dir is missing

core/artwork.go, ui/src/subsonic/index.js
This PR improves performance for placeholder images:
- Use a common URL for placeholder images allowing browsers to cache the image
- Applies requested size to the placeholder image reducing transfer size
I'm leaving this as a draft for now as I don't know if there are negative impacts from removing the `updatedAt` field from the getCoverArt requests for placeholders. 
**Original behavior**
Original behavior has to make a request for each placeholder image at original size. My system/internet has lousy upload performance resulting in noticeable delay in fetching placeholders.
**New behavior**
With the following changes only a single request for the place holder is performed, and at a reduced size.
=> Improve performance of placeholder images

db/migration/20210821212604_add_mediafile_channels.go, model/mediafile.go, scanner/mapping.go, scanner/metadata/ffmpeg/ffmpeg.go, scanner/metadata/ffmpeg/ffmpeg_test.go, scanner/metadata/metadata.go, scanner/metadata/metadata_test.go, scanner/metadata/taglib/taglib_test.go, scanner/metadata/taglib/taglib_wrapper.cpp, ui/src/album/AlbumSongs.js, ui/src/common/SongDetails.js, ui/src/i18n/en.json, ui/src/playlist/PlaylistSongs.js, ui/src/song/SongList.js
First off awesome project! I'm looking to get familiar with the codebase to start adding a few missing features for classical music (https://github.com/navidrome/navidrome/issues/1036). I'm starting off small and figured this would be a good contribution although not in the linked issue since it is especially for those with multi-channel versions of the same track in their library.
I'm fairly new to Go as well so let me know if anything is off on that front.  With regards to the current changes two things I wasn't able to piece together:
* the naming convention for the `db/migration` file
* the configuration for prettier. It looks like `SongList.js` needs to run it.
If I missed anything regarding the contributing conventions let me know.
Cheers!
=> feat: Adds Audio Channel Metadata - #1036

ui/src/audioplayer/Player.js
Fixes #1397.
Currently the state of `scrobbled` will be set to `false` every time the player begins playing (including it being unpaused) which will cause duplicate scrobbles.
This fix has `scrobbled` only be reset in the `onAudioPlayTrackChange` and `onAudioEnded` events. The reason both events are needed is that `onAudioEnded` will not fire when the player moves to the next track and `onAudioPlayTrackChange` will not fire if the player is set to repeat.
=> Only reset player scrobbled state on track change or end

ui/src/themes/useCurrentTheme.js
This allows the UI to gracefully recover from the state having an invalid theme set (for instance while developing a custom theme and then switching branches)
=> Handle invalid theme in ui state

ui/src/themes/monokai.js
Contains a pretty simple styling fix to accompany the new Monokai theme introduced in https://github.com/navidrome/navidrome/pull/1669.
=> Fixes a coloring glitch with the Monokai theme "unauthorized" popup

cmd/root.go
`break` is incorrect here, as it just breaks out of the select.
`return` to exit the function instead.
Fixes #1636.
=> Fix signaler not exiting on cancel

server/server.go
Changes were made in https://github.com/navidrome/navidrome/commit/2a3cd08f201d30385f3e2b76b6b11d5f5e1d70b2 to add `ReadHeaderTimeout`, but the router was not added to the new server, resulting in 404s for every access. This fix restores prior functionality.
=> Fix server 404s

server/middlewares.go, server/subsonic/middlewares.go
Closes Issue #1776 
Description:
* None is deprecated and will fallback to Lax in the future, it currently throws a warning on Firefox. [Details on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)
* Using Strict is future proof and provides additional CSR protection
* Using Strict caused no regressions in my tests
Changes
* Change SameSite from None to Strict in server/middlewares.go for `X-ND-Client-Unique-Id` cookie
* Add SameSite Strict setting to server/subsonic/middlewares.go (was unset) for `nd-player` cookie
=> fix:(middlewares.go) - Set Cookie SameSite mode to Strict - 1776

.devcontainer/devcontainer.json
Docker requires volumes to be mounted with a SELinux flag (on SELinux enabled systems) to make sure, the volume directory gets SELinux context accessible inside the container. This PR changes the devcontainer config to disable the default workspace mount and adds a custom one that includes the SELinux flag.
`:Z` stands for a volume that cannot be shared between different contains (and `:z` is for shared volumes).
Additional information:  
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
=> Mount devcontainer workspace in a SELinux compatible way

ui/src/dialogs/AddToPlaylistDialog.js, ui/src/dialogs/AddToPlaylistDialog.test.js
Closes #1604 
Fixes previously existing functionality of showing a warning if a track is already present when adding it to a playlist.
Behavior when skipping a song already in a playlist
Behavior when adding a song already in a playlist
=> fix(UI): Warn if track is already present when adding to playlist - 1604

ui/src/themes/index.js, ui/src/themes/nord.css.js, ui/src/themes/nord.js
I've polished off the Nord theme tpbnick created.
Do let me know if there's anything you reckon I should adjust!
Also apologies for creating a separate pull request for this, I don't know how to attach it to the pre-existing one (if that's even possible).
=> Nord Theme

db/migration/20220724231849_add_musicbrainz_release_track_id.go, db/migration/migration.go, model/mediafile.go, scanner/mapping.go, scanner/metadata/metadata.go, scanner/metadata/metadata_test.go
Uniquely identifies the track within an album, unlike `musicbrainz_trackid`. See https://picard-docs.musicbrainz.org/downloads/MusicBrainz_Picard_Tag_Map.html.
Prerequisite for https://github.com/navidrome/navidrome/pull/1363, but is good to have anyway.
Includes a bonus typo fix.
=> Capture "musicbrainz_releasetrackid" tag

consts/consts.go
Handy for Bluetooth clients, they can usually pass the stream straight through without re-encoding.
=> consts: add aac default transcoding

core/agents/listenbrainz/client.go, core/agents/listenbrainz/client_test.go
This sends the content type header with all requests to Listenbrainz servers.
The lack of this header causes some listenbrainz implementations (e.g. the one in [maloja](https://github.com/krateng/maloja)) to interpret the body as a string.
For example, in maloja the request would be interpreted as:
```js
{
'{"listen_type":"playing_now","payload":[{"track_metadata":{"artist_name":"TootArd","track_name":"Laissez Passer","release_name":"Laissez Passer","additional_info":{"tracknumber":1,"track_mbid":"c6a62b3f-a225-4ead-a71d-dc3119f3f7d4","artist_mbids":["f991e662-1ed9-45e9-9cd1-84eee4529146"],"release_mbid":"c97ea6f9-15c6-4508-a0f2-d4ce8e02383e"}}}]}': '',
}
```
instead of
```js
{
"listen_type": "playing_now",
"payload": [{
"track_metadata": {
"artist_name": "TootArd",
"track_name": "Laissez …
```
=> fix: send content type header in listenbrainz requests - #1944

cmd/wire_gen.go, conf/configuration.go, core/archiver.go, core/media_streamer.go, server/subsonic/stream.go, ui/src/App.js, ui/src/actions/dialogs.js, ui/src/album/AlbumActions.js, ui/src/album/AlbumList.js, ui/src/album/AlbumSongs.js, ui/src/artist/ArtistList.js, ui/src/common/ContextMenus.js, ui/src/common/SongContextMenu.js, ui/src/dialogs/DownloadMenuDialog.js, ui/src/i18n/en.json, ui/src/playlist/PlaylistActions.js, ui/src/playlist/PlaylistSongs.js, ui/src/reducers/dialogReducer.js, ui/src/song/SongList.js, ui/src/subsonic/index.js
Closes: #573
Enables transcoding downloaded songs, albums, playlist, and artists. 
To support transcoding downloads, I added two new parameters to the download API
- format: the target format to transcode to (the name, like mp3, opus)
- bitrate: the rate to transcode all songs. A value of 0 (or not provided) means to use the original bitrate
Optionally, with `AutoTranscodeDownlaod` set to true, downloads can be automatically transcoded using the transcoding configuration in the UI.
On the frontend, downloads now have a modal asking for a download choice: either use the original format, or transcode to a different format and optionally choose a bitrate. From the Navidrome UI, all download requests would provide the optional parameters above.
I tried my best to add minimal new text, but …
=> Enable transcoding of downlods

core/transcoder/transcoder.go, go.mod, utils/cache/file_caches.go, utils/cache/file_caches_test.go
Don't cache transcoded files if the request was cancelled or when there was a transcoding error. 
There's no way for `fscache` to detect errors while writing to the cache, so I had to use an 'invalidate cache' approach similar to @FoxBuru's PR #1996
Fix #1950
=> Don't cache transcoded files if the request was cancelled 

ui/src/album/AlbumList.js, ui/src/album/AlbumTableView.js, ui/src/i18n/en.json, ui/src/song/SongList.js
Resolves #1974. Adds createdAt as a `DateField` with times shown, and modifies all translation files that already had a `createdAt` key.
=> Add created at column for albums, songs table

ui/src/album/AlbumExternalLinks.js, ui/src/artist/ArtistExternalLink.js
This PR refers to #1513.
If the config option `lastFMEnabled` is set to false, the LastFM icons on the artist and album pages will not be shown.
Although in #1488, @deluan [mentions](https://github.com/navidrome/navidrome/issues/1488#issuecomment-979462507) that showing these buttons is intended behaviour, as it's not an 'integration' and if the user doesn't click on them, then there's technically no connection to LastFM. However, this is not very clear for users, and there's talk in #1513 of making a separate 'External services' toggle instead.
=> Hide LastFM icons if `config.lastFMEnabled` is false

ui/src/audioplayer/styles.js
Closes #2089.
Adds the media query and if reduced motion is preferred, sets `animation: none`.
Screenshots or Videos
Related Issues and Pull Requests(if any) #2089
=> fix(ui): does not respect prefers-reduced-motion #2089

scanner/metadata/taglib/taglib_wrapper.go
Build currently fails on Illumos with error `Undefined symbol sendfile`. Fix it by linking `sendfile` explicitly.
Output before patch:
```
$ GOOS=illumos CGO_ENABLED=1 gmake build
WARNING: This command does not build the frontend, it uses the latest built with 'make buildjs'
go build -ldflags="-X github.com/navidrome/navidrome/consts.gitSha=62609270 -X github.com/navidrome/navidrome/consts.gitTag=v0.48.0-SNAPSHOT" -tags=netgo
/opt/local/go118/pkg/tool/solaris_amd64/link: running g++ failed: exit status 1
Undefined                       first referenced
symbol                             in file
sendfile                            /tmp/go-link-1916572260/go.o
ld: fatal: symbol referencing errors. No output written to $WORK/b001/exe/a.out
collect2: error: ld returned 1 exit status
gmake: …
```
=> fix(taglib): Fix Illumos build - #2067

ui/src/playlist/PlaylistList.js
This PR is modeled after https://github.com/navidrome/navidrome/pull/1219. Unlike song view, playlist view doesn't have comment and genre columns available, so this PR adds it.
=> Playlist view: optionally show genre and comment columns

.github/workflows/pipeline.yml, .goreleaser.yml
This reverts commit 1374dab08775d3fefff96dbe707675e0d1a766d3 and fix the issue with `goreleaser` not able to get the version from Git, resulting in versions like `v0.0.0`
=> Fix versioning releases in the pipeline

core/external_metadata.go, server/public/public_endpoints.go, server/subsonic/api.go
When refreshing stale external metadata (from Last.fm or Spotify), limit concurrent refreshes to a just one and give some time between them. This will help with both rate limits and alleviating CPU usage.
This is done for both `artistInfo` and `albumInfo` (one queue for each).
Address issues in #2130
=> Optimizations to External Metadata refresh

ui/src/themes/nord.css.js
Personally, I found the shadow made it hard enough to read Latin characters. However, it is even harder to read other fonts (from my experience, Chinese and Japanese). This reduces the stroke weight to be clearer.
Original:
Current:
I did want to preserve at least some of the shadow (since it's a cool effect). If that's not worth it, here is also how it looks without shadow
=> Make lyrics on Nord theme easier to read

core/artwork/artwork.go, core/artwork/artwork_internal_test.go, core/artwork/image_cache.go, model/artwork_id.go, model/artwork_id_test.go, server/public/encode_id_test.go, server/subsonic/browsing.go, server/subsonic/helpers.go, server/subsonic/searching.go
This should help with invalidating artwork cache client-side.
Ref: https://support.symfonium.app/t/refresh-cover-for-single-albums/1434
=> Add lastUpdated to `coverArt` ids

ui/src/audioplayer/Player.js
Addresses #2167
Safari expects audioContext.resume() to be called in a function that is _directly_ related. For Navidrome, this means that any click that could start playing tracks should first call resume. This also includes the player itself, which happens when you refresh the page. Unfortunately, because react-jinke-player's onAUdioPlay isn't a direct user action, I had to manually add an event listener.
Additionally, we don't connect the audio context in the first place if replaygain is not enabled for the user.
=> Call resumeContext directly

ui/src/SharePlayer.js
When testing the original fix, I did not notice that the background was impacted (it was always light). This PR is a more proper fix that preserves the background. New view (I had to delete `.light-view` from `.react-jinke-music-player-main`). Sorry for the bugged first attempt .-.
=> Limit share size while handling theme properly

.gitignore, contrib/docker-compose/Caddyfile, contrib/docker-compose/docker-compose-caddy.yml, contrib/docker-compose/docker-compose-traefik.yml, contrib/docker-compose/docker-compose.yml
as discussed in https://github.com/navidrome/navidrome/issues/476
=> add docker compose examples, with traefik or caddy and without, fixes #476

cmd/wire_gen.go, conf/configuration.go, core/archiver.go, core/share.go, core/share_test.go, db/migration/20230310222612_add_download_to_share.go, model/errors.go, model/share.go, resources/i18n/pt.json, server/public/handle_downloads.go, server/public/handle_shares.go, server/public/public.go, server/serve_index.go, server/serve_index_test.go, ui/src/App.js, ui/src/config.js, ui/src/dialogs/ShareDialog.js, ui/src/i18n/en.json, ui/src/share/ShareEdit.js, ui/src/share/ShareList.js, ui/src/share/SharePlayer.js, ui/src/utils/urls.js
This PR introduces an new config option, `DefaultDownloadableShare`, to set what is the default to use when sharing.
Each share can be set as "downloadable" individually, and this can be changed after the share is created.
Fix #2125
=> Add option to make shares downloadable

server/subsonic/album_lists.go, server/subsonic/api.go, server/subsonic/browsing.go, server/subsonic/helpers.go, server/subsonic/playlists.go, server/subsonic/responses/responses.go, server/subsonic/responses/responses_test.go, server/subsonic/searching.go, server/subsonic/sharing.go
Fixes issues with malformed tags breaking clients. Ex:
- http://support.symfonium.app/t/subsonic-source-navidrome-music-files-only-show-under-files-folder/1606/6
- http://support.symfonium.app/t/music-is-only-viewable-from-the-files-category-despite-working-yesterday-and-resyncing-with-my-server/1614/4
=> Convert all Subsonic API ints to int32 as per specification

persistence/mediafile_repository_test.go, persistence/sql_annotations.go
Closes #2262
Update play_date on scrobble only when newer
Make `annotation.play_date` set to `max` of the existing value and the new value.
(None)
(None)
=> fix(persistence): Update play_date on scrobble only when newer - #2262

contrib/navidrome.service
This appears to be used by newer go versions and navidrome fails to start unless it's allowed.
Fixes #1961
=> fix(systemd): allow the setrlimit syscall - #1961

contrib/k8s/README.md, contrib/k8s/manifest.yml
- This adds a basic K8s manifest in order to run Navidrome in Kubernetes.
- Users will have to adjust the manifest to fit their use case, but this a place to start.
=> Add K8s manifest

Makefile, cmd/root.go, conf/configuration.go, consts/consts.go, core/media_streamer.go, core/media_streamer_Internal_test.go, core/media_streamer_test.go, tests/init_tests.go, utils/cache/file_caches.go, utils/cache/file_caches_test.go
As briefly discussed on discord, this PR adds a config option to specify the cache directory. I added it as a CLI argument too (`--cachefolder`), as well as the usual config option (`CacheFolder`) and env var (`ND_CACHEFOLDER`).
This will allow linux distributions (eg: alpine, since I maintain the navidrome package on that one) to put the navidrome cache to `/var/cache/navidrome`.
I wasn't sure what default value to put between just `./cache` or `<datafolder>/cache`. Opted for `./cache` for now.
I haven't updated the website to add the new config option, I'll do once we agree on this MR / values, etc.
=> Allow configuring cache folder

scanner/playlist_importer.go, tests/fixtures/playlists/subfolder1/.hidden_playlist1.m3u, tests/fixtures/playlists/subfolder2/.hidden_playlist2.m3u
Closes #2367 
I added the same code from tag scanner to ignore files starting with a dot "." and a couple of hidden playlist for the tests.
=> fix(playlist): Ignore playlists starting with a dot - #2367

ui/src/themes/ligera.js
Description: Certain bits of text were unreadable when using the Libera theme, due to them being the same color as the background.
Changes: This changes those text sections to be their correct color.
**Before:**
**After:**
=> fix(theme): Fix certain text being unreadable with Libera

core/playback/device.go, core/playback/mpv/mpv.go, core/playback/mpv/track.go, core/playback/playbackserver.go
This PR fixes a bug and a typo and aligns the configuration file syntax with mpv's audio device syntax.
Here's an example:
```
Jukebox.Enabled = true
Jukebox.Devices = [
[ "internal",     "coreaudio/BuiltInSpeakerDevice" ],
[ "dac",          "coreaudio/AppleUSBAudioEngine:Cambridge Audio :Cambridge Audio USB Audio 1.0:0000:1" ]
]
Jukebox.Default = "dac"
```
=> Jukebox cleanup

model/criteria/criteria_test.go, model/criteria/fields.go
Currently, if a track does not have a genre, adding a genre filter will cause the track to be ignored (null comparison). This PR converts null to empty string.
=> [bugfix]: coalesce genre to null for smart playlist

core/external_metadata.go
In reference to https://github.com/navidrome/navidrome/issues/1701
The gist is: Navidromes "findMatchingTrack" function should try to match from albumartist direct releases *first*, *then* from compilation albums.
=> improve TopSongs findMatchingTrack by de-prioritizing compilations

go.mod, go.sum, scanner/mapping.go, scanner/metadata/metadata.go, utils/cache/spread_fs.go
Linux support for btime in [djherbis/times](https://github.com/djherbis/times) has just been merged: https://github.com/djherbis/times/pull/13 . So we can now implement btime on all platforms, and finally close https://github.com/navidrome/navidrome/issues/1350
Behaviour is very simple: use `btime` for Date Added, if there is no `btime` (for example on ext2 volumes), then it falls back to `time.Now()`, like Navidrome currently does.
edit: 1.6.0 of the `times` package has now been released, tests work, so ready to go
=> Use file creation date for Date Added/CreatedAt

server/server_test.go, ui/package.json
`server/server_test.go` & `ui/package.json` have hardcoded IPv4 literals = bad practice - will fail on systems without IPv4 stack
=> Fix hardcoded IPv4 literals

ui/src/artist/ArtistExternalLink.js
Currently, if you have an artist with no lastfm link but they have a musicbrainz id, the links are broken; this PR addresses that. Resolves #2370
=> Fix external link for artist page if LastFM is missinb but Musicbrainz is not

model/artist.go, persistence/artist_repository.go, scanner/refresher.go, tests/mock_artist_repo.go
Currently, on a full refresh, the artist metadata is cleared entirely and the updated timestamp is set to 0 (needs refresh). This PR changes this by only updating the necessary fields (but still marking metadata as old).
=> Do not empty old artist metadata

scanner/tag_scanner.go, scanner/walk_dir_tree.go, scanner/walk_dir_tree_test.go
Fix #2630 
Description:
After discussing with @deluan , we've come to the conclusion that `fs.Fs` is not suitable for our use case. So we decided to revert back to using the `os` package.
For more details see https://github.com/golang/go/issues/44279
=> Fix scanner on Windows

persistence/album_repository.go, persistence/mediafile_repository.go, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .JSON, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .XML, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 without data should match .JSON, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 without data should match .XML, server/subsonic/responses/.snapshots/Responses Child with data should match .XML, server/subsonic/responses/.snapshots/Responses Child without data should match .JSON, server/subsonic/responses/.snapshots/Responses Child without data should match .XML, server/subsonic/responses/responses.go, server/subsonic/responses/responses_test.go, server/subsonic/searching.go
Fix #2642
Change how the `AlbumID3` json marshal works to fix `getAlbum` endpoint. And add genres to search results.
=> Fix OpenSubsonic endpoints that include Genres

scanner/metadata/taglib/taglib_wrapper.go
Fix the `ld: warning: ignoring duplicate libraries` warning message when building and testing.
=> Fix ld warnings on taglib_wrapper.

conf/configuration.go, persistence/album_repository.go, persistence/artist_repository.go, persistence/mediafile_repository.go
Fixes #643
Navidrome traditionally sort albums, artists and songs by using the name/title tag and removing the articles from the prefix (Ex: "The Beatles" => "Beatles"). See the [IgnoredArticles](https://www.navidrome.org/docs/usage/configuration-options/#:~:text=Empty%20(disabled)-,IgnoredArticles,-ND_IGNOREDARTICLES) config option.
This PR introduces a new `PreferSortTags` (`ND_PREFERSORTTAGS`), `false` by default. If set to true, Navidrome will try to use any sort tag (sorttitle, sortalbumname, sortartistname) if found, if not it falls back to the previous behaviour. 
This flag does not require a full scan.
@certuna, I'd like your opinion on this. Please let me know what you think.
=> Add new PreferSortTags option

server/auth.go
`remoteAddr` returns `@` when listening on a UNIX socket, which breaks reverse proxy auth. This PR allows `@` on `unix:` path to go through
=> [bugfix]: allow reverse proxy auth for unix socket

model/criteria/json.go, model/criteria/operators.go, model/criteria/operators_test.go
> A smart playlist can use the playlist name for filtering. This can be used to create combined playlists or to filter multiple playlists.
I am a bit unsure about the two new left joins. They work the same way as the `genre` filter. It would be great, if they are only used when we actually filter by `genre` or a `playlist`. But there seems to be no easy way to do this (I guess?) as the fields are already processed into a query long before the left joins are appended.
=> feat: Add playlist field to smart playlists - #1417

persistence/playlist_repository.go, persistence/playlist_track_repository.go
Resolves #2816 
As @flyingOwl reported in his issue, some information was no longer being displayed on subsonic clients. This is due to the switch from orm to dbx that was made in 0ca0d5da228a5c2810c6103185891272ade1cdbf.
This fix makes sure that the rows affected have the correct names.
=> Fix fields not being sent on getPlaylist responses.

ui/src/common/RatingField.js
The value can either be a number or `null` (when selecting the same rating). Convert null to 0 because the backend doesn't accept null.
=> [bugfix]: set rating to 0 when value is null

server/subsonic/helpers.go, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .JSON, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .XML, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 without data should match .JSON, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 without data should match .XML, server/subsonic/responses/responses.go, server/subsonic/responses/responses_test.go
Formalizes support for https://github.com/opensubsonic/open-subsonic-api/pull/68. Also makes `originalReleaseDate` actually optional
=> [enhancement]: OS expose release date for album, make original optional

.github/workflows/pipeline.yml, .golangci.yml
- Update workflow
- use linter configuration instead of `exclude-rules`
- the default Go version is based on the `go.mod`
=> Improves golangci-lint configuration and workflow

resources/i18n/fa.json
The original "انگلیسی" is "English"
=> fix: languageName for Persian

core/playback/mpv/track.go
in #2771 there are still some bugs with the jukebox mode
this PR solves one of the errors by fixing the get Position() function in case mpv errors out and needs multiple retries.
without this patch, the function directly returns
=> fix bug in jukebox: property unavailable

scanner/cached_genre_repository.go
I think this fixes https://github.com/navidrome/navidrome/issues/2003
In the testing I've done, the obvious growth in memory (with scanning every minute) is instances of the cache within the Cached Genre Repository. I'm not 100% if this is the only leak contributing to that issue, but it was definitely the largest contributor for me. 
I've not dug into the ttlcache code, but it appears that it is never GC'd and I'm assuming that the library is not built to be used with many dynamically created instances of the cache, previously every time that the scanner was run, the ttlcache was also created each time. This caused (under testing with 166 genres in the database) the memory consumed by navidrome to 101.18MB over approx 3 days; 96% of which is in instances of this cache. Swapping to a …
=> Fixing Memory Leak in CachedGenreRepository

.github/workflows/pipeline.yml, core/artwork/artwork.go, core/artwork/artwork_internal_test.go, core/artwork/artwork_test.go, core/artwork/cache_warmer.go, core/artwork/reader_resized.go, core/artwork/sources.go, server/public/handle_images.go, server/subsonic/media_retrieval.go, server/subsonic/media_retrieval_test.go, ui/src/album/AlbumGridView.js, ui/src/subsonic/index.js
Fix AlbumGrid shaking when a non-square album cover is rendered.
=> Fix image stuttering.

scanner/metadata/metadata.go, scanner/metadata/metadata_internal_test.go
OPUS files are supposed to have R128 gain tags instead of the regular ReplayGain ones: https://datatracker.ietf.org/doc/html/rfc7845#section-5.2.1
This spec targets a loudness of -23dB as opposed to ReplayGain's -18dB.
So what I do is this, if a file does not have a ReplayGain tag, I proceed to check the existence the corresponding R128 track. Then I calculate the dB adjustment and add 5dB to it so that the target loudness ends up being the same as that ReplayGain. This seems like the simplest approach.
=> Add R128_{TRACK,ALBUM}_GAIN support to the scanner

server/serve_index.go, server/serve_index_test.go, ui/src/personal/Personal.js
Regardless of if `LastFM.Enabled` was true in the configuration, navidrome would set it to false based on if LastFM API and secret were set. This was done so that navidrome coulkd determine if it should display the "Scrobble to Last.fm" toggle switch in the personal settings screen. 
This pr removes that logic, and checks if `lastfm-apikey` is set in the local storage instead.
Fixes #3076
=> fix disappearing LastFM links

persistence/sql_base_repository.go
Currently, if you have random sort and genre filter, you get an error
```
`SELECT coalesce(starred, 0) as starred, coalesce(rating, 0) as rating, starred_at, play_date, coalesce(play_count, 0) as play_count, album.* FROM album LEFT JOIN annotation on (annotation.item_id = album.id AND annotation.item_type = 'album' AND annotation.user_id = 'user-id') LEFT JOIN album_genres ag on album.id = ag.album_id LEFT JOIN genre on ag.genre_id = genre.id WHERE (genre_id = {:p0}) ORDER BY SEEDEDRAND('album-id', id) asc LIMIT 18`  args="map[p0:genre-id]" elapsedTime="...µs" error="ambiguous column name: id" requestId= rowsAffected=0 username=...
```
This is because the `id` field in `SEEDRAND` is ambiguous. This PR adds the table name to the id field to make this id unambiguous.
=> [bugfix]: fix album/media file random sort

ui/src/themes/nord.js
Resolves #2667. _Something_ changed that resulted in the background of the Nord theme being different. This PR restores the original background (the value below would be `#303030`)
=> [bugfix]: Fix background color for nord theme

core/players.go, core/players_test.go, core/scrobbler/play_tracker.go, db/migrations/20240802044339_player_use_user_id_over_username.go, model/player.go, persistence/persistence_suite_test.go, persistence/persistence_test.go, persistence/player_repository.go, persistence/player_repository_test.go
This PR primarily resolves #1928 by switching the foreign key of `player` from `user.user_name` to `user.id`. There are also a few other fixes/changes:
- For some bizarre reason, `ip_address` is never returned from `read`/`get`. Change the field to `ip`, which works. Somehow
- Update `players_test.go` mock to also check for user agent, replicating the actual code
- Update `player_repository.go` `isPermitted` to check user id. I don't know how this worked before...
- tests!
- a few places referred to `typ`, when it is really `userAgent`. Change the field names
=> [bugfix] player: use userId, other fixes

.devcontainer/devcontainer.json
I noticed that the Go version was outdated when I jumped back in the dev container running the latest code. I have updated that and also moved VSCode specific options to adhere to the latest dev container json spec.
=> Update dev container to use Go 1.23 and customizations object

core/media_streamer.go
Closes #3226 
The `selectTranscodingOptions` function in the `core/media_streamer.go` deserved some love in the form of better readability and maintainability.
- Split the `selectTranscodingOptions` function into three smaller functions.
- Simplified the conditional logic.
=> refactor(core): Refactor selectTranscodingOptions function - #3226

server/nativeapi/playlists.go
If you have a smart playlist with sort `random`, when going through multiple pages the smart playlist will be constantly refreshed resulting in inconsistent behavior.
This PR fixes this behavior by only refreshing the playlist on the first page (`_start=0`).
=> [bugfix]: Only refresh smart playlist when fetching first track

conf/configuration.go, model/criteria/criteria.go, model/criteria/criteria_test.go, model/criteria/operators.go, persistence/playlist_repository.go, persistence/playlist_repository_test.go
Fixes #3017 
This PR ensure that when a smart playlist is refreshed, the playlists used in its rules also have their tracks refreshed first.
This is my first time diving into the Navidrome codebase and using the Go language, so if there is anything I need to do to improve the code here please let me know and I'll be happy to fix it up!
=> Recursively refresh playlist tracks within smart playlist rules

persistence/sql_base_repository.go
Fixes reseedeng in the backend for random sort.
~~I _personally_ think `AlbumList.js` would be better without `filter={{ seed: version }}` (as you have to refresh for it to change), but that's another choice.~~
=> Fixes reseeding for random

ui/src/album/AlbumList.js
Resolves #3277. Basically, get a random seed on browser reload. Selecting `Random` will still update the version.
Maybe a better rng would be appropriate?
=> random seed for album list on page reload

persistence/artist_repository.go, persistence/artist_repository_test.go, persistence/export_test.go, persistence/persistence_suite_test.go, scanner/metadata/taglib/taglib_test.go
Closes #3285
Description
Navidrome is modified so that when the Subsonic getArtists API is executed, if the setting PreferSortTags is true, the value of index should be created using sort_artist_name.
Changes
- getIndexKey: Fixed the process of getting the original value of index.
- GetIndex: Fix sorting when retrieving records from table artist so that all artists with equal index values are included in the same index tag.
- Add test of getIndexKey. 
- Modify test of GetIndex.
=> fix(scanner): sort_artist_name to be used when  indexing performers if PreferSortTag is true

persistence/sql_restful.go, persistence/sql_restful_test.go
If you type a ' (or other ignored symbols) in the search bar, it gives you an internal server error instead of the ' being treated as text on a search.
Some chars are removed from the search query, and when it was empty (after removing all ignored chars), if tried to create a null SQL clause, causing a panic.
Thanks @repomansez for reporting this.
=> fix: crash on empty filters

persistence/playqueue_repository.go, server/subsonic/bookmarks.go
To clear the users' Play Queue, call `savePlayQueue` without any `id`.
See: https://github.com/opensubsonic/open-subsonic-api/pull/106#event-14682075631
=> feat(os): support clearing play queue

server/subsonic/browsing.go, server/subsonic/helpers.go, server/subsonic/responses/.snapshots/Responses Artist with data and MBID and Sort Name should match .JSON, server/subsonic/responses/.snapshots/Responses Artist with data and MBID and Sort Name should match .XML, server/subsonic/responses/.snapshots/Responses Artist with data should match .JSON, server/subsonic/responses/.snapshots/Responses Artist with data should match .XML, server/subsonic/responses/.snapshots/Responses Artist without data should match .JSON, server/subsonic/responses/.snapshots/Responses Artist without data should match .XML, server/subsonic/responses/responses.go, server/subsonic/responses/responses_test.go
`getArtists` and `getIndexes` return `ArtistID3`, which has mbid and sort name. This PR changes the type from `Artist` to `ArtistID3`, and also makes the attributes **not** `omitempty`, as they are required to be empty per OS.
=> feat(subsonic): Add MusicBrainz ID and Sort Name to Index

core/artwork/reader_album.go, core/artwork/reader_mediafile.go, core/artwork/sources.go, go.mod, go.sum
Tries these images in order to find the proper embedded cover:
- Search for images with description matching "cover" AND "front"
- Search for images with description matching "front"
- Search for images with description matching "cover"
- Fallback to first image if none of the above is found
Fix #3254
This uses a `dhowden/tag` fork for now. See https://github.com/dhowden/tag/issues/109
=> fix(server): try to find proper embedded front cover - only for vorbis comments for now

core/media_streamer.go, core/media_streamer_Internal_test.go
=> fix: forcing transcoding when client does not specify transcoding options

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Navidrome Guru](https://gurubase.io/g/navidrome) to Gurubase. Navidrome Guru uses the data from this repo and data from the [docs](https://www.navidrome.org/docs) to answer questions by leveraging the LLM.
In this PR, I showcased the "Navidrome Guru", which highlights that Navidrome now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, …
=> Introducing Navidrome Guru on Gurubase.io

ui/bin/update-workbox.sh, ui/src/sw.js
`precacheAndRoute` is not a global. Add the proper import to prevent service worker from crashing.
=> (bugfix): Fix service worker crashing on precacheAndRoute

ui/src/common/ContextMenus.jsx, ui/src/common/PlayButton.jsx
Closes: #3557
Change the AlbumListView and context menu's play buttons so that they sort by `album` instead of `trackNumber`
=> fix(ui): fix play queue for play button and context menus

.dockerignore, Makefile, cmd/root.go, conf/configuration.go, consts/consts.go, core/metrics/insights.go, core/metrics/insights/data.go, core/metrics/insights_linux.go, model/player.go, persistence/player_repository.go
=> fix(insights): improving reports

Dockerfile
As documented in the OCI Image Format, [org.opencontainers.image.source](https://github.com/opencontainers/image-spec/blob/5325ec48851022d6ded604199a3566254e72842a/annotations.md#L24) identifies an image's source repository. This is purely for documentation purposes. It does however help tools such as [Renovate](https://docs.renovatebot.com/modules/datasource/docker/#description) to find the changelogs when a new Navidrome version is released. The changelogs would then be included in the PR Renovate creates.
Just as an example, here's a screenshot of a Renovate PR which cannot find Navidrome's changelogs, so they are simply omitted.
<details>
<summary>Example...</summary>
</details>
=> docs: Set org.opencontainers.image.source label in Dockerfile

cmd/root.go
Fixes Navidrome not exiting cleanly on stop.
=> fix(server): use cancellable context instead of Sleep for initial insights delay

model/share.go, server/public/handle_shares.go, server/public/public.go
The URL for the m3u will be the same as the Share URL, just add a /m3u at the end. Example:
https://myserver/share/G3zqpMpHK8 => https://myserver/share/G3zqpMpHK8/m3u
See https://github.com/navidrome/navidrome/discussions/3651
=> feat(server): create M3Us from shares

resources/i18n/ru.json
- Adds missing strings added in the past couple releases
- Improves share-related translations for clarity
- Changed "Общий доступ" (literally "common access") to "Ссылка доступа" ("shared-access link(s)")
- Updated "Поделился" ("he shared") to "Кто поделился" ("who shared")
- Translate "downloading" as "скачивание" instead of its synonym "загрузка", to match the word used on download links elsewhere.
=> fix(ui) Update Russian translation

core/inspect.go, server/nativeapi/inspect.go, ui/src/common/SongContextMenu.jsx
- Use `mediaFileId` instead of `id` for playlist tracks
- Only fetch if the file is not missing
- If extractor fails to get the file, also error (rather than panic)
=> fix(ui): Fix playlist track id, handle missing tracks better

ui/src/artist/ArtistShow.jsx
- use maximum of albumartist/artist credits for determining pagination
- reduce default maxPerPage considerably. This gives values of 36/72/108 at largest size
=> feat(ui): Improve Artist Album pagination

scanner/walk_dir_tree.go, utils/time.go, utils/time_test.go
Currently, the `images_updated_at` field is only set to the image modification time. However, in cases where a new image is added _and_ said image is older than the folder mod time, the field is not updated properly.
In this the case where `images_updated_at` is null (no images were ever added) and a new images is found, use the folder modification time instead of image modification time.
**Note**, this doesn't handle cases such as replacing a newer image with an older one.
=> fix(scanner): Always refresh folder image time when adding first image

db/migrations/20241026183640_support_new_scanner.go
=> fix(server): db migration does not work for MusicFolders ending with a trailing slash.

resources/mappings.yaml
With old metadata, Disc Subtitle was one of `tsst`, `discsubtitle`, or `setsubtitle`. With the updated, `setsubtitle` is only available for flac. Update `mappings.yaml` to maintain prior behavior.
=> chore(tags): Restore setsubtitle as discsubtitle for non-WMA

consts/consts.go, model/metadata/map_mediafile.go, model/metadata/map_participants.go, model/metadata/map_participants_test.go, server/subsonic/helpers.go
Should fix #3808
Rules:
- ARTIST(S) tags No ARTIST/ARTISTS tags should set the display name to Unknown Artist
- ARTIST(S) tags No ARTIST/ARTISTS tags should set artist to Unknown Artist
- ARTIST(S) tags No ARTIST/ARTISTS tags should add an Unknown Artist to participants
- ARTIST(S) tags Single-valued ARTIST tags, no ARTISTS tags should use the artist tag as display name
- ARTIST(S) tags Single-valued ARTIST tags, no ARTISTS tags should populate the participants
- ARTIST(S) tags Multiple values in a Single-valued ARTIST tags, no ARTISTS tags should use the full string as display name
- ARTIST(S) tags Multiple values in a Single-valued ARTIST tags, no ARTISTS tags should split the tag
- ARTIST(S) tags Multiple values in a Single-valued ARTIST tags, no ARTISTS tags should split the tag using …
=> fix(scanner): fix displayArtist logic

release/wix/navidrome.wxs
Previously most of the ini settings were using `addLine` would add-or-update, resulting in the custom settings being overridden on upgrade. `createLine` will only add to the ini if the key doesn't already exist, which port was using correctly.
=> Fixing msi upgrades overwriting some custom ini settings

core/ffmpeg/ffmpeg.go
This pull request includes a change to the `core/ffmpeg/ffmpeg.go` file to improve the command used for extracting images with FFmpeg.
* [`core/ffmpeg/ffmpeg.go`](diffhunk://#diff-a9b3e13d6a71ca846882c8ea135dc820571c5f7f895da5ce0d8e78fce2e43c2aL32-R32): Modified the `extractImageCmd` to use `-map 0:v -map -0:V` instead of `-an` for better video stream selection.
- `-map 0:v` selects all video streams from the input
- `-map -0:V` excludes all "main" video streams (capital V)
This combination effectively selects only the attached pictures.
Fixes #3859
=> fix(server): better embedded artwork extraction with ffmpeg

conf/configuration.go, model/metadata/map_participants.go, ui/src/common/ArtistLinkField.jsx, ui/src/common/ArtistLinkField.test.jsx
This pull request introduces changes to enhance the handling of artist and remixer metadata, improve the configuration options, and add comprehensive testing for the `ArtistLinkField` component. The most important changes include adding a new configuration option for the artist joiner, updating the metadata mapping to use this new configuration, and refactoring the `ArtistLinkField` component to handle artists and remixers more effectively.
* [`conf/configuration.go`](diffhunk://#diff-5b7f9f2790a5795a69654b2ba8c72112da865800efa1110b181c6c70de96c9dbR132): Added a new configuration option `Scanner.ArtistJoiner`, default value is `" • "`. 
* [`model/metadata/map_participants.go`](diffhunk://#diff-75c16e7d655baae2b572f2b738a59420bd568f2f45672360e4644b3a678060d2L213-R215): Updated the …
=> feat(server): custom ArtistJoiner config

db/migrations/20241026183640_support_new_scanner.go, scanner/phase_1_folders.go
It was skipping folders for certain timezones.
This bug would manifest as all your artists have 0 albums/songs after you finish upgrading to 0.55.X.
If you already upgraded to 0.55.0 or 0.55.1, and don't have the old backup to try upgrading again, just wait the number of hours your timezone is ahead of UTC (ex: CEST = 1hour), and manually trigger a full scan.
=> fix(bfr): force upgrade to read all folders.

ui/src/album/AlbumList.jsx, ui/src/album/AlbumTableView.jsx, ui/src/song/SongList.jsx
This PR addresses issue #3924 by adding a toggleable mood column to both Album and Song list views.
- Added a mood column to Album and Song list views
- Column displays only the first mood tag value from the tags
- Column is hidden by default (added to defaultOff)
- Column can be toggled via the column selector menu
This allows users to see mood tag values directly in the list views when they choose to enable the column.
=> Add mood column to Album and Song list views

server/auth.go, server/auth_test.go
Fixes #3902 - When Navidrome is accessed for the first time through a reverse proxy with authentication headers (Remote-User), it creates a regular non-admin user. This prevents the normal "first user is admin" flow, leaving the system without an admin user.
- Modified the `handleLoginFromHeaders` function in `server/auth.go` to check if there are any existing users before creating a new user
- If there are no existing users, the first user created via reverse proxy is now made an admin
- Added unit tests to verify this behavior
Added new test cases to verify:
1. The first user created via reverse proxy is made an admin
2. Subsequent users created via reverse proxy are not made admins
This change maintains consistent behavior with manual user creation where the first user is always an …
=> Fix #3902: Make first user created via reverse proxy an admin

core/artwork/reader_album.go, core/artwork/reader_album_test.go, model/mediafile.go, model/mediafile_test.go
Album cover art selection wasn't correctly prioritizing disc numbers over file paths, leading to inconsistent cover art selection in multi-disc albums. This affected both embedded artwork in media files and external cover art images in album folders.
Previously, with a folder structure like:
```
Artist/Album/Disc1/cover.jpg
Artist/Album/Disc2/cover.jpg
Artist/Album/Disc3/cover.jpg
```
Navidrome would always pull the cover from the lowest disc number, but after a recent update, multi-disc albums were pulling artwork from random discs.
This PR includes two related fixes:
1. Fixed the `firstArtPath` function in `model/mediafile.go` to properly prioritize media files with the lowest disc number when selecting album artwork from embedded covers, regardless of the file path. If disc numbers are …
=> fix(artwork): always select the coverArt of the first disc in multi-disc albums

conf/configuration.go, core/scrobbler/play_tracker.go, core/scrobbler/play_tracker_test.go
Removed all code, config, and test references to DevEnableBufferedScrobble. 
- Buffered scrobbling is now always enabled. 
- Added this option to the list of deprecated config options with a warning.
- Updated all logic and tests to reflect this.
=> chore: remove DevEnableBufferedScrobble and always enable buffered scrobbling

resources/mappings.yaml
Something I just found out, but some taggers also add `unsyncedlyrics` (e.g., flac) for unsynced lyrics (instead of just `lyrics`). Add this to the default mapping (since I think it just makes sense).
=> chore(mappings): add unsynced lyrics to default mapping

conf/configuration.go, scanner/walk_dir_tree.go, scanner/walk_dir_tree_test.go
Fixes #4060
This PR adds a new configuration option `Scanner.FollowSymlinks` (default: true) to control whether the filesystem scanner should follow symbolic links when scanning directories.
Changes:
1. Added new configuration option `Scanner.FollowSymlinks` (default: true)
2. Modified `isDirOrSymlinkToDir` to respect this option
3. Added comprehensive tests to verify both enabled and disabled behavior
4. Converted tests to use `DescribeTable` for better maintainability
The option can be configured in `navidrome.toml`:
```toml
[Scanner]
FollowSymlinks = false  # Set to false to skip symlinks
```
Or via environment variable:
```bash
ND_SCANNER_FOLLOWSYMLINKS=false
```
=> feat(scanner): add Scanner.FollowSymlinks option

Makefile
The IDs of the artists changed from the BFR update. So this PR just updates them to the new ones in the Makefile.
=> fix(Makefile): Update Makefile music URLs

.gitignore, AGENTS.md, model/tag.go, server/subsonic/helpers.go, server/subsonic/responses/.snapshots/Responses AlbumList with OS data should match .JSON, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .JSON, server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .XML, server/subsonic/responses/.snapshots/Responses Child with data should match .JSON, server/subsonic/responses/.snapshots/Responses Child with data should match .XML, server/subsonic/responses/.snapshots/Responses Child without data should match OpenSubsonic .JSON, server/subsonic/responses/responses.go, server/subsonic/responses/responses_test.go
- support new `isrc` field on OpenSubsonic `Child`: https://github.com/opensubsonic/open-subsonic-api/discussions/123
- include `isrc` values when building responses from `MediaFile`
- introduce `model.TagISRC` constant
- `make test`
=> Add ISRC support for OpenSubsonic Child

core/agents/lastfm/agent.go, core/agents/lastfm/agent_test.go, core/agents/listenbrainz/agent.go, core/agents/listenbrainz/agent_test.go, core/scrobbler/buffered_scrobbler.go, core/scrobbler/buffered_scrobbler_test.go, core/scrobbler/interfaces.go, core/scrobbler/play_tracker.go, core/scrobbler/play_tracker_test.go, plugins/adapter_scrobbler.go, plugins/api/api.pb.go, plugins/api/api.proto, plugins/api/api_vtproto.pb.go, plugins/examples/discord-rich-presence/plugin.go, server/subsonic/media_annotation.go, server/subsonic/media_annotation_test.go, ui/src/audioplayer/Player.jsx, ui/src/subsonic/index.js
- extend `scrobble` endpoint with optional `position` parameter
- store playback offset in play tracker and forward to scrobblers
- expose `position` in plugin `TrackInfo` and update Discord plugin to use it
- send current playback offset from the UI when resuming playback
- add regression test covering position handling
- remove stray binary from repository
- `go test -tags netgo ./...`
- `npm test --silent`
=> Add playback position to scrobble NowPlaying

model/artist.go, persistence/artist_repository.go, persistence/artist_repository_test.go, persistence/persistence.go, server/subsonic/browsing.go, ui/src/artist/ArtistList.jsx, ui/src/dataProvider/wrapperDataProvider.js
- add `missing` field to artist model
- support missing flag when fetching artist indexes
- mark artists with only missing albums as missing in GC
- expose missing filter to UI wrapperDataProvider
- update Subsonic browsing to exclude missing artists by default
- `make test`
=> Handle missing artists for regular users

core/artwork/cache_warmer.go, core/artwork/cache_warmer_test.go, utils/cache/file_caches.go, utils/cache/file_caches_test.go
- stop cache warmer when the file cache is disabled
- expose `Disabled` method on `FileCache`
- avoid buffering artwork when cache can't run
- test cache warmer disabled behaviour
- test `FileCache.Disabled`
- `make test`
=> Fix memory leak in cache warmer

persistence/sql_base_repository.go, persistence/transcoding_repository.go, persistence/transcoding_repository_test.go
This pull request introduces role-based access control (RBAC) for the `transcodingRepository` by restricting certain operations to admin users only. It also adds comprehensive unit tests to validate the new behavior. The key changes include the addition of an `isAdmin` function, integration of permission checks across repository methods, and new test cases for admin and regular user scenarios.
* Added `isAdmin(ctx context.Context) bool` function to check if the current user has admin privileges. (`persistence/sql_base_repository.go`, [persistence/sql_base_repository.goR68-R72](diffhunk://#diff-6c854194ab908411d5d3b72b0121abdb9f2ac4caf24c8410139b35fdeaa87d47R68-R72))
* Integrated `isAdmin` checks into the following methods of `transcodingRepository` to restrict operations for non-admin …
=> fix(transcoding): restrict transcoding operations to admin users

core/artwork/artwork.go, core/artwork/artwork_internal_test.go, core/artwork/reader_artist.go, core/artwork/reader_artist_test.go
- unskip artwork internal tests and update for folder-based covers
- generate temporary cover images in tests
- adjust expectations to match current behavior
- `make test PKG=./core/artwork`
=> Fix ignored artwork tests

persistence/mediafile_repository_test.go, server/nativeapi/missing.go, ui/src/dataProvider/wrapperDataProvider.js, ui/src/i18n/en.json, ui/src/missing/DeleteMissingFilesButton.jsx, ui/src/missing/DeleteMissingFilesButton.test.jsx, ui/src/missing/MissingFilesList.jsx, ui/src/missing/MissingListActions.jsx
- allow deleting all missing files via native API when no ids are provided
- update dataProvider to omit query string on DELETE without ids
- support delete-all option in DeleteMissingFilesButton
- add Remove All button to missing files list
- add translations for Remove All
- test delete-all button behaviour
- test DeleteAllMissing in media file repository
- `npm run lint`
- `npm run check-formatting`
- `npm run test:ci`
- `npm run type-check`
- `make test`
=> Add remove all missing files functionality

.github/copilot-instructions.md, model/criteria/criteria.go, model/criteria/criteria_test.go, model/criteria/fields.go, model/criteria/operators_test.go, model/tag_mappings.go
- cast tag values to numeric when numeric args are used in smart playlist rules
- test numeric comparison for custom tag
- `make test`
=> Fix numeric comparisons for float custom tags

conf/configuration.go, core/agents/lastfm/agent.go, core/agents/lastfm/agent_test.go
This pull request introduces a new configuration option, `ScrobbleFirstArtistOnly`, for Last.fm integration. The option allows users to specify whether only the first listed artist should be scrobbled for tracks with multiple artists. The changes include updates to configuration handling, the Last.fm agent logic, and associated tests.
* Added a new field, `ScrobbleFirstArtistOnly`, to the `lastfmOptions` struct in `conf/configuration.go` to support the new configuration option.
* Set the default value for `ScrobbleFirstArtistOnly` to `false` in the `setViperDefaults` function.
* Introduced a new method, `getArtistForScrobble`, in `core/agents/lastfm/agent.go` to determine the artist to scrobble based on the `ScrobbleFirstArtistOnly` configuration. Updated the `NowPlaying` and `Scrobble` …
=> feat(server): add option `Lastfm.ScrobbleFirstArtistOnly` to send only the first artist

ui/src/playlist/PlaylistSongs.jsx
------
Closes: #1676, #3225
This PR addresses an issue, where being on page 2 or greater of a playlist, then immediately navigating to a different playlist that has less pages than the current page number will result in an 'empty' page with no songs or pagination options.
This is achieved via the `useEffect` hook in the `PlaylistSongs` component, calling `setPage(1)` whenever the playlist changes. It will also automatically scroll to the top of the page, but this can be removed if it is undesirable.
=> bugfix(playlist): reset page to 1 on playlist change - #1676

core/artwork/reader_artist.go, core/artwork/reader_artist_test.go
Fixed the bug where `artist.jpg` files in artist folders were not detected for new artists with only one album. This issue occurred because the original `fromArtistFolder` implementation only searched in the calculated artist folder without any fallback mechanism.
**Specific scenario that was failing:**
- New artist with only 1 album
- `artist.jpg` file present in the artist folder
- File was not being picked up and displayed in the UI
- Once a second album was added and library re-scanned, the `artist.jpg` file would then be recognized
Enhanced the `fromArtistFolder` function to implement **directory traversal fallback** for finding artist images:
1. **Directory Traversal**: Search up to 3 levels (artist folder + 2 parent levels)
2. **Priority Order**: Always prioritizes images found in …
=> fix: enhance artist folder detection with directory traversal

conf/configuration.go, resources/i18n/pt-br.json, server/nativeapi/config.go, server/nativeapi/config_test.go, server/nativeapi/native_api.go, server/serve_index.go, server/serve_index_test.go, ui/src/App.jsx, ui/src/common/SongInfo.jsx, ui/src/config.js, ui/src/dialogs/AboutDialog.jsx, ui/src/i18n/en.json, ui/src/utils/toml.js, ui/src/utils/toml.test.js
- Added the `DevUIShowConfig` flag to expose configuration options through the UI and set its default to `true`
- Included the new flag in the UI configuration injection so the front end can display the config tab when enabled
- Registered the /config route and implemented the handler to list all configuration values with admin-only access
- Updated the front-end default config to respect devUIShowConfig and added translations for the new tab
- Modified AboutDialog to include the new “Configuration” tab for admin users, fetching data from the new endpoint
- Redact sensitive information (APIKeys, Secrets) server-side
- `make test PKG=./...`
- `npm run lint`
- `npm run check-formatting`
- `npm run test`
- `npm run type-check`
=> Add configuration tab in About dialog

model/playlist.go, persistence/playlist_repository.go, persistence/playlist_repository_test.go, server/nativeapi/native_api.go, server/nativeapi/playlists.go, ui/src/common/SongContextMenu.jsx, ui/src/common/SongContextMenu.test.jsx, ui/src/dataProvider/wrapperDataProvider.js, ui/src/i18n/en.json
- expose GetPlaylists method on PlaylistRepository
- add REST endpoint to list playlists for a track
- extend SongContextMenu with Show in Playlist submenu
- add translations and tests
- `make test`
- `npm run lint`
- `npm run check-formatting`
- `npm test`
- `npm run type-check`
=> Add 'Show in Playlist' context menu

cmd/scan.go, scanner/controller.go, scanner/scanner.go
Proper fix: the problem with metrics not being updated was that `scanAll` was happening in a gofunc/separate process, so it was not updating the primary instance properly. Move this call outside the subprocess.
Note: `navidrome scan` will not update metrics, but this should be tackled as a separate issue.
=> fix(scannner): use prometheus instance over noop if configured properly

core/playback/mpv/mpv.go, core/playback/mpv/mpv_suite_test.go, core/playback/mpv/mpv_test.go, core/playback/mpv/track.go, go.mod
This pull request introduces improvements to the MPV playback command handling and adds comprehensive testing for the `mpv` module. Key changes include the adoption of a shell-parsing library to handle complex command templates, better error handling for invalid arguments, and the addition of unit tests to ensure robustness.
* Replaced naive string splitting with `shellquote.Split` for parsing the `MPVCmdTemplate`, allowing proper handling of quoted arguments and spaces in paths.
* Enhanced error handling in `createMPVCommand` and `start` functions to return meaningful errors when arguments are invalid or missing. [[1]](diffhunk://#diff-82e1c6f991157881db00233150f0b269ffb5739bf888ad68aacfb7a2c246a037R13-R21) [[2]](diffhunk://#diff-d2cc4e3c47c0f7e4d54c013589956d458fe36095cf82d2075d3db00d9c1 …
=> Fix mpv command and template parsing

server/subsonic/users.go, server/subsonic/users_test.go
Fixes the bug where `GetUser` was incorrectly setting `jukeboxRole` to `true` for all users when jukebox was enabled, regardless of the `Jukebox.AdminOnly` configuration setting.
This PR also refactors the code to eliminate duplication between `GetUser` and `GetUsers` methods.
- Fixed `GetUser` method to properly implement jukebox role logic: `!conf.Server.Jukebox.AdminOnly || user.IsAdmin`
- Previously it was simply setting `JukeboxRole = conf.Server.Jukebox.Enabled` ignoring the AdminOnly setting
- **Extracted `buildUserResponse()` helper function** to eliminate ~30 lines of duplicated code between `GetUser` and `GetUsers`
- **Fixed username field inconsistency**: `GetUsers` was incorrectly using `loggedUser.Name` instead of `loggedUser.UserName`
- **Improved maintainability**: User …
=> Fix JukeboxRole logic in GetUser to respect AdminOnly setting

persistence/playlist_track_repository.go, server/nativeapi/native_api.go, server/nativeapi/playlists.go, ui/src/common/RatingField.jsx, ui/src/common/useRating.jsx, ui/src/common/useRating.test.js, ui/src/common/useToggleLove.jsx, ui/src/common/useToggleLove.test.js, ui/src/playlist/PlaylistSongs.jsx
This PR implements rating and love/star functionality for tracks when viewed in playlists.
**Backend:**
- Added `GET /api/playlist/{id}/tracks/{id}` endpoint for fetching individual playlist tracks
- Fixed SQL queries in `playlist_track_repository.go` to properly qualify column names and return playlist track objects instead of media files
- Added `getPlaylistTrack` handler function with proper middleware setup
**Frontend:**
- Modified `RatingField` and `useRating` to use `mediaFileId` when available (for playlist tracks) instead of the playlist track ID
- Updated `useToggleLove` with similar logic to target the underlying media file for star/unstar operations
- Added rating column to playlist songs view and enabled love functionality in context menus
- Both rating and love hooks now …
=> Add Love and Rating functionality to playlist tracks

core/scrobbler/play_tracker.go, core/scrobbler/play_tracker_test.go, resources/i18n/pt-br.json, server/events/events.go, ui/src/actions/serverEvents.js, ui/src/eventStream.js, ui/src/i18n/en.json, ui/src/layout/AppBar.jsx, ui/src/layout/NowPlayingPanel.jsx, ui/src/layout/NowPlayingPanel.test.jsx, ui/src/reducers/activityReducer.js, ui/src/reducers/activityReducer.test.js, ui/src/subsonic/index.js, ui/src/subsonic/index.test.js, utils/cache/simple_cache.go, utils/cache/simple_cache_test.go
This PR adds a "Now Playing" panel to the Navidrome UI that displays currently playing tracks from all users. The panel shows real-time information about what music is being played across the system. This panel is only visible to admins.
- **Now Playing Panel**: A new slide-out panel accessible from the app bar
- **Real-time Updates**: Uses server-sent events to update the count of currently playing tracks
- **Responsive Design**: Works on both desktop and mobile with appropriate styling
- **User Information**: Displays username, player name, and current track information
- **Artist Navigation**: Clicking on artist names navigates to the artist page
- Enhanced the play tracker to send `NowPlayingCount` events via the event broker
- Added proper event handling for tracking when tracks …
=> feat(ui): add Now Playing panel and integrate now playing count updates

release/goreleaser.yml
This small PR updates the GoReleaser configuration to resolve the following warnings which you can find in the [CI logs](https://github.com/navidrome/navidrome/actions/runs/15662056257/job/44121333198#step:6:28): 
```
DEPRECATED: archives.format_overrides.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat_overridesformat for more info
```
=> fix: update GoReleaser configurations

model/artist.go, persistence/artist_repository.go, scanner/scanner.go, scanner/scanner_test.go, tests/mock_artist_repo.go
After PR #4059, full scans were not forcing a refresh of all artists. During a full scan, only artists with recently updated media files would have their stats refreshed, leaving other artists with potentially stale statistics.
This PR implements a clean solution that ensures all artist stats are refreshed during full scans:
1. **Set `changesDetected = true` for full scans** - This ensures all maintenance operations (GC, library stats refresh, etc.) run automatically during full scans
2. **Add `allArtists` parameter to `RefreshStats()`** - Makes the intent explicit:
- When `allArtists = true`: Refresh stats for **all artists** 
- When `allArtists = false`: Refresh stats for **touched artists only** (original behavior)
3. **Pass `fullScan` state to `RefreshStats`** - The scanner now passes …
=> fix: ensure full scan refreshes all artist stats

model/request/request.go, persistence/artist_repository.go, scanner/phase_1_folders.go, scanner/scanner_test.go, server/nativeapi/missing.go
Artist statistics were not being refreshed correctly in two scenarios:
1. **During quick scans**: Newly added albums didn't result in their artists being marked as "touched", so incremental RefreshStats operations would skip them
2. **After missing file deletion**: When missing files were deleted, related artists weren't being updated, leaving stale statistics
The issue stemmed from the RefreshStats method relying on artist `updated_at` timestamps to determine which artists need refreshing, but:
- During scanning, artists were saved without updating the `updated_at` field
- During missing file deletion, artist records remained untouched even though their stats should change
**Two-part fix:**
- Added `"updated_at"` to the list of columns when calling `artistRepo.Put()`
- Ensures artists …
=> Fix artist stats not refreshing during quick scan and after missing file deletion

cmd/root.go, cmd/wire_gen.go, cmd/wire_injectors.go, core/metrics/prometheus.go, plugins/adapter_media_agent.go, plugins/adapter_media_agent_test.go, plugins/adapter_scheduler_callback.go, plugins/adapter_scrobbler.go, plugins/adapter_websocket_callback.go, plugins/host_scheduler_test.go, plugins/host_websocket_test.go, plugins/manager.go, plugins/manager_test.go, plugins/manifest_permissions_test.go, plugins/runtime_test.go, plugins/wasm_base_plugin.go, scanner/controller.go, server/subsonic/album_lists_test.go, server/subsonic/api.go, server/subsonic/media_annotation_test.go, server/subsonic/media_retrieval_test.go, server/subsonic/middlewares.go, server/subsonic/opensubsonic_test.go, server/subsonic/playlists_test.go
This exposes the following metrics:
- Subsonic
- Method counts by endpoint, HTTP method, and HTTP code
- Latency (50%, 90%, 99% quartiles), as well as total elapsed
- Plugin
- Calls by plugin name, method, and whether the response is ok. Note that this _should_ ignore nil/not implemented responses.
- Same latency calculations as latency
Note that prometheus is now a singleton, so that it can be passed around much easier to plugins.
Consequently, the scan metrics require passing in the database now.
I'd like to also support native API, but that's trickier as there are URL fragments.
=> Add prometheus metrics to subsonic and plugins

.gitignore, db/migrations/20250701010105_remove_dangling_items.sql
When upgrading from version 0.54.5 or older (pre-BFR), there are some edge cases that can cause albums and songs to be duplicated in a library, and because of bad DB relationships, they are never deleted/marked as missing, with no way to removing them from the DB.
This PR marks these items as missing on startup, so they become deletable from the Missing Files view.
Should fix #4081
=> Clear dangling music from BFR migration 

conf/configuration.go, core/agents/agents.go, core/agents/agents_test.go, core/external/provider.go, core/external/provider_topsongs_test.go
Since providers may not know what artists are in the DB and thus return more than the limit, filter the artists _after_ the fact to ensure that no more than `limit` number of similar artists are returned.
=> fix(provider): ensure that similar artists retreived from provider are no more than limit

persistence/mediafile_repository.go, persistence/mediafile_repository_test.go, ui/src/song/SongList.jsx
This PR fixes issue #4046 by implementing RecentlyAddedByModTime configuration support for individual tracks/mediafiles.
The RecentlyAddedByModTime configuration setting only worked for albums, not for individual tracks. When sorting tracks by "Date Added", the system would always use created_at regardless of the configuration setting.
- Added `mediaFileRecentlyAddedSort()` function to respect the RecentlyAddedByModTime configuration
- Added `recently_added` sort mapping to mediafile repository that uses modification time when configured
- Implemented proper test coverage for both configuration scenarios
- Updated SongList.jsx to use `sortBy="recently_added"` for the "Date Added" column
- This ensures the UI uses the correct backend sort key that respects the configuration
Closes #4046
=> feat: implement RecentlyAddedByModTime support for tracks (#4046)

core/metrics/prometheus.go, model/request/request.go, server/subsonic/api.go, server/subsonic/api_test.go, server/subsonic/middlewares.go
The current implementation was using HTTP status code, which is almost always 200. Instead, pass in a pointer to the error code and update `sendResponse` and use that instead.
=> fix(prometheus): report subsonic error code

db/migrations/20250701010107_add_mbid_indexes.sql, persistence/album_repository.go, persistence/artist_repository.go, persistence/artist_repository_test.go, persistence/mediafile_repository.go, persistence/mediafile_repository_test.go, persistence/sql_restful.go, persistence/sql_restful_test.go, persistence/sql_search.go
This PR enhances the Subsonic API search functionality to support searching by MusicBrainz ID (MBID) for albums, artists, and media files. This improvement provides more accurate and efficient searches when users have MBID information available.
The implementation prioritizes MBID searches over full-text searches when valid UUIDs are detected, providing better search accuracy for users with MusicBrainz-tagged music libraries.
1. Start Navidrome with a music library that contains tracks with MBID metadata
2. Use the search functionality with valid MBID values (UUIDs)
3. Verify that searches return appropriate results for albums, artists, and tracks with matching MBIDs
4. Run the test suite: `make test PKG=./persistence/...`
**Key Changes:**
- Updated …
=> feat: MBID search functionality for albums, artists and songs

cmd/wire_gen.go, cmd/wire_injectors.go, conf/configuration.go, plugins/adapter_media_agent.go, plugins/adapter_media_agent_test.go, plugins/adapter_scheduler_callback.go, plugins/adapter_scrobbler.go, plugins/adapter_websocket_callback.go, plugins/host_scheduler.go, plugins/host_scheduler_test.go, plugins/host_websocket.go, plugins/host_websocket_test.go, plugins/manager.go, plugins/manager_test.go, plugins/manifest_permissions_test.go, plugins/plugin_lifecycle_manager_test.go, plugins/runtime.go, plugins/runtime_test.go
This PR fixes issues with plugin-related warnings and directory creation that were impacting users when plugins are disabled. The changes ensure that plugin operations are only performed when plugins are actually enabled.
**Key Changes:**
1. **Silenced repeated "Plugin not found" warnings**: Eliminated spam warnings for inactive Spotify/Last.fm agents when plugins are disabled
2. **Fixed plugin folder creation**: Ensured the plugin folder is only created when plugins are enabled, preventing permission errors in restrictive environments
3. **Improved plugin system efficiency**: Plugin loading operations are now completely bypassed when `Plugins.Enabled = false`
Fixes #4292 - This PR addresses the "permission denied" error when creating the plugins directory in environments where plugins …
=> fix: silence plugin warnings and folder creation when plugins disabled

core/playback/mpv/mpv_test.go
Not all systems have bash at `/bin/bash`. `/bin/sh` is POSIX and we can trust it to be present. We don't use any bash features in this simple script so should should be an easy, portable change.
Fixes #4301
In an environment without /bin/bash attempt to run the mpv tests and note the
ones that execute the test sh script fail.
`go test -tags=netgo -count=1 ./core/playback/mpv`
=> test(fix): Use /bin/sh as interpreter for mock_mpv.sh - 4301

adapters/taglib/end_to_end_test.go, adapters/taglib/taglib_test.go, adapters/taglib/taglib_wrapper.cpp
DSF/DSD (or, at least Picard) appears to store cover art in APIC field (ID3). Extract this in taglib for `has_cover`
Also make reading from wma a bit safer, fix the tests, and read from WavPack (APE tags only, not ID3v1).
Fixes #4278 
I could not for the life of me figure out how to trim a DSF file to 1 second. So, to test:
1. Get a DSD file from https://www.oppodigital.com/hra/dsd-by-davidelias.aspx
2. Use Picard to embed cover art
3. Verify `navidrome inspect $file` shows `"hasCoverArt": true,`
4. Verify that Navidrome, with `Agents` set to an empty string, shows the embedded cover art for the album and song
For the other formats, just `make test PKG=./adapters/taglib`
Inspect output:
[inspect_output.json](https://github.com/user-attachments/files/ …
=> fix(taglib): read cover art from dsf, wavpak, fix wma test

plugins/api/errors.go, plugins/wasm_base_plugin.go
This PR improves the plugin system's error handling and metrics recording functionality. The changes provide better clarity between different error types and ensure that metrics are only recorded for actual plugin operations, not for "not implemented" responses.
- **Refactored `callMethod` function** in `wasm_base_plugin.go` to use the `api.ErrNotImplemented` error instead of the previously used `agents.ErrNotFound`
- **Improved metrics recording logic** to exclude "not implemented" responses from metrics, preventing noise in monitoring data
The main improvements include:
1. **Metrics accuracy**: Only actual plugin operations are recorded in metrics, not capability checks
2. **Better tracing**: Enhanced context propagation for debugging plugin operations
Please review and check all that …
=> Improve plugin error handling and metrics recording

ui/src/artist/ArtistActions.test.jsx, ui/src/artist/actions.js
This PR fixes the bug where artist radios (similar songs) were ignoring replaygain information, causing songs to be played at much louder volumes than when played manually.
The issue was that the `getSimilarSongs2` and `getTopSongs` Subsonic API endpoints return replaygain data in a different format (`replayGain` object) than what the frontend expects (`rgAlbumGain`, `rgAlbumPeak`, `rgTrackGain`, `rgTrackPeak` fields). This PR adds proper mapping between these formats to ensure replaygain information is correctly passed to the playback system.
Fixes #4299
1. Enable replaygain in Navidrome settings
2. Ensure your music library has files with replaygain tags
3. Start an artist radio from any artist page
4. Verify that songs play at the expected volume …
=> Fix replaygain mapping for Subsonic Artist Radio and Top Songs

plugins/README.md, plugins/api/api.pb.go, plugins/api/api.proto, plugins/api/api_plugin_dev_named_registry.go, plugins/host/scheduler/scheduler.pb.go, plugins/host/scheduler/scheduler.proto, plugins/host/scheduler/scheduler_host.pb.go, plugins/host/scheduler/scheduler_plugin.pb.go, plugins/host/scheduler/scheduler_vtproto.pb.go, plugins/host_scheduler.go, plugins/host_scheduler_test.go
This PR adds a new `TimeNow` function to the SchedulerService plugin system that returns the current time in multiple formats for plugin use. This enhancement allows plugins to access current time information in standardized formats without requiring additional host services.
- Added `TimeNow` RPC method to scheduler.proto
- Returns current time in three formats:
- `rfc3339_nano`: RFC3339 format with nanosecond precision
- `unix_milli`: Unix timestamp in milliseconds
- `local_time_zone`: Local timezone name (e.g., "UTC", "America/New_York")
- **Protocol Buffer Definition**: Added `TimeNowRequest` (empty) and `TimeNowResponse` messages
- **Go Implementation**: Added `TimeNow` method to `SchedulerHostFunctions` interface and `schedulerService` …
=> feat(plugin): add TimeNow function to SchedulerService

core/share.go, model/tag.go, persistence/artist_repository.go, persistence/artist_repository_test.go, persistence/genre_repository.go, persistence/genre_repository_test.go, persistence/persistence_suite_test.go, persistence/scrobble_buffer_repository.go, persistence/share_repository.go, persistence/share_repository_test.go, persistence/sql_base_repository.go, persistence/sql_base_repository_test.go, persistence/sql_participations.go, persistence/sql_tags.go, persistence/tag_library_filtering_test.go, ui/src/artist/ArtistList.jsx
Fixes headless library access issues in Navidrome by improving library filtering logic and resolving SQL ambiguity errors in share queries.
1. Set up a Navidrome instance with multiple libraries
2. Test library access with both authenticated and headless operations
3. Verify that share queries execute without SQL ambiguity errors
4. Confirm that library filtering is applied correctly in all scenarios
- Fixed user context validation in `applyLibraryFilterToArtistQuery`
- Improved join order and conditional logic for library filtering
- Resolved SQL ambiguity errors in share queries
- Ensured library access works correctly for both authenticated and headless operations
- `fe2a2204c`: Enable library access for headless processes
- `946265823`: Resolve …
=> fix: headless library access improvements

Makefile, persistence/album_repository_test.go, persistence/sql_participations.go
This PR fixes foreign key constraint errors during album scanning when albums are spread across multiple folders. The issue was caused by participant (artist) insertion attempting to reference artist IDs that don't exist in the database, resulting in "FOREIGN KEY constraint failed" errors that prevented album scanning from completing.
The fix implements automatic filtering of non-existent artist IDs during participant insertion using SQLite's `json_each` function with an `INNER JOIN` to the artist table. This ensures only valid artist references are inserted into the album_artists and media_file_artists tables.
Fixes #4002
The issue does not occur consistently. The situation described in #4002 may not reproduce the issue. This may be caused by the …
=> fix: prevent foreign key constraint errors in album participant insertion

ui/src/layout/ActivityPanel.jsx, ui/src/layout/ActivityPanel.test.jsx
This PR improves the user experience of the activity panel by resetting the error icon to its normal state when the user clicks on it, while preserving the error message visibility within the panel itself.
**Problem:** Previously, when a scan error occurred, the activity panel icon would remain in an error state (showing an error icon) indefinitely, even after the user opened the panel to view the error details. This created visual noise and didn't provide a way for users to acknowledge they had seen the error.
**Solution:** The icon now returns to its normal state after the user clicks it for the first time, indicating they have acknowledged the error. The error message remains visible in the activity panel, ensuring users can still access the error details.
This addresses a UX …
=> Reset activity panel error icon to normal state when clicked

core/playlists.go, core/playlists_test.go
Fixes playlist import issues for songs with accented characters from Apple Music M3U playlists. The problem occurred because Apple Music exports M3U playlists with Unicode NFC (Canonical Composed) encoding while macOS filesystem normalizes paths to NFD (Canonical Decomposed) encoding, causing path mismatches during playlist import.
Fixes #3332
1. **Run specific Unicode tests**: Use `go test -v ./core -ginkgo.focus "normalizePathForComparison|Unicode normalization"` to run only the Unicode-related tests
2. **Integration testing** (optional): 
- Create a test M3U file with paths containing accented characters (both NFC and NFD encoded)
- Place it in a monitored playlist directory 
- Verify that songs are correctly matched during playlist sync
N/A - …
=> Fix playlist import for songs with accented characters

resources/i18n/bs.json
Update translations for Bosnian language
This pull request adds a complete and natural translation of the Navidrome interface into the Bosnian language (`bs.json`). All German labels, actions, fields, messages, and UI text have been carefully translated and adapted to sound natural and user-friendly for native speakers.
_No related issues._
It's just a new language file.
1. Place the `bs.json` file in the appropriate `i18n` directory of Navidrome.
2. Start Navidrome and select **Bosnian** from the language settings.
3. Verify that all UI elements, messages, and labels are translated and displayed correctly.
_Not applicable – this is a language translation only._
- Translation is localized for Bosnian (`bs`) and written in a natural, user-friendly …
=> Created bs.json
