.gitignore
persistence/persistence_suite_test.go
scanner/change_detector.go
scanner/change_detector_test.go
scanner/metadata_ffmpeg.go
scanner/metadata_test.go
scanner/scanner_suite_test.go
scanner/tag_scanner.go

Fix issue when MusicFolder is a relative path (starting with '.')

---

Makefile
conf/configuration.go
consts/consts.go
engine/cover.go
engine/cover_test.go
engine/engine_suite_test.go
engine/media_streamer.go
engine/media_streamer_test.go
engine/wire_providers.go
wire_gen.go

Also fixes handling unexpected situations when loading the artwork from files, and now always return a default image in case of any errors
Also changes the default image for albums without cover

Implements artwork cache

---

scanner/metadata_ffmpeg.go

Improve ffmpeg's error diagnostic

---

ui/package-lock.json
ui/package.json
ui/src/App.js
ui/src/album/AlbumList.js
ui/src/audioplayer/Player.js
ui/src/i18n/en.js
ui/src/i18n/index.js
ui/src/i18n/pt.js
ui/src/layout/PersonalMenu.js
ui/src/personal/Personal.js
ui/src/song/SongList.js
ui/src/subsonic/index.js

Add translations

---

engine/list_generator.go
model/mediafile.go
persistence/album_repository.go
persistence/album_repository_test.go
server/subsonic/album_lists.go
server/subsonic/album_lists_test.go
server/subsonic/api.go
server/subsonic/responses/responses.go

Implement `byYear` and `byGenre`
Bump Subsonic API version to 1.10.2

New Subsonic API endpoints

---

ui/package-lock.json
ui/package.json
ui/src/i18n/fr.js
ui/src/i18n/index.js

Add French localization

---

server/server.go
server/subsonic/api.go

#184: Configuration for throttling only for media group requests

request throttling only for media group api

---

ui/src/audioplayer/Player.js
ui/src/audioplayer/queue.js
ui/src/store/createAdminStore.js

Turn off autoplay when reloading the play queue from the Redux store

---

contrib/navidrome.service

I'm not sure if I should create a new one, or just update this one.

Update the sample navidrome.service for use in Arch Linux

---

conf/configuration.go
server/app/app.go
server/app/serve_index.go
ui/src/common/DocLink.js
ui/src/common/index.js
ui/src/config.js
ui/src/i18n/en.js
ui/src/personal/Personal.js
ui/src/transcoding/TranscodingEdit.js
ui/src/transcoding/TranscodingList.js
ui/src/transcoding/TranscodingNote.js
ui/src/transcoding/TranscodingShow.js
ui/src/transcoding/index.js
ui/src/utils/docsUrl.js

Add config option to enable/disable Transcoding configuration

---

Makefile

I just hit this step during my first build. Easy to workaround, but it may help others.

Add a npm install step in the build

---

db/migration/20200512104202_add_disc_subtitle.go
model/mediafile.go
persistence/album_repository.go
persistence/mediafile_repository.go
scanner/metadata_ffmpeg.go
scanner/tag_scanner.go
ui/src/album/AlbumSongs.js
ui/src/common/SongDetails.js

Import and display disc subtitles

---

go.mod
go.sum

Fix https://github.com/deluan/navidrome/issues/318

Fix Opus cover art

---

cmd/root.go
cmd/scan.go
cmd/wire_gen.go
cmd/wire_injectors.go

This allows the server to have scan disabled (`ScanInterval=0`), and manually trigger the scan when needed

Add a `scan` option to command-line

---

persistence/album_repository.go
resources/i18n/pt.json
ui/src/App.js
ui/src/album/AlbumList.js
ui/src/album/albumLists.js
ui/src/i18n/en.json
ui/src/layout/Menu.js
ui/src/personal/Personal.js

This PR implements album lists views (similar to Airsonic): Random, Recently Added, Recently Played, Most Played.
Remaining tasks:
Fix: #201

Implement album lists

---

cmd/wire_gen.go
db/migration/20200731095603_create_play_queues_table.go
engine/common.go
model/datastore.go
model/playqueue.go
persistence/mock_persistence.go
persistence/persistence.go
persistence/playqueue_repository.go
persistence/playqueue_repository_test.go
server/subsonic/api.go
server/subsonic/bookmarks.go
server/subsonic/browsing.go
server/subsonic/helpers.go
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses Bookmarks with data should match .JSON
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses Bookmarks with data should match .XML
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses Bookmarks without data should match .JSON
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses Bookmarks without data should match .XML
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses PlayQueue with data should match .JSON
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses PlayQueue with data should match .XML
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses PlayQueue without data should match .JSON
server/subsonic/responses/.snapshots/responses-snapshotMatcher-Match-Responses PlayQueue without data should match .XML
server/subsonic/responses/responses.go
server/subsonic/responses/responses_test.go
server/subsonic/wire_gen.go
server/subsonic/wire_injectors.go
utils/request_helpers.go
utils/request_helpers_test.go

This PR bumps Subsonic API to version 1.12.0, which may cause some differences, and possible issues with players tested with the previous version (1.10.0). One visible difference is that now DSub exposes some features that are not totally ready (artist images, artist radio, etc..), but it should not break it

Support Bookmarks and Save/Get PlayQueue

---

resources/i18n/fr.json

- *Correct typos in the French translations* (I tried to do this in POEditor)

Correct French translations

---

ui/src/album/AlbumActions.js
ui/src/playlist/PlaylistActions.js

I work as a developer professionally, but this is my first ever open source contribution.
I've felt a smaller change like this would be suitable for my first time!
Regarding the change itself.. I guess it's pretty clear what it is doing.
It is a function that I was looking for myself, so I decided to just go ahead and implement it.

Adding play later buttons to album / playlist views (actions)

---

resources/i18n/zn.json

Added the translation of some entries in the Chinese language

test，del blank

---

resources/i18n/es.json

Spanish translation

---

scanner/metadata/taglib/taglib_parser.go

Fix compilation of C++ code on certain linux systems

---

ui/src/audioplayer/Player.js
ui/src/audioplayer/PlayerToolbar.js
ui/src/common/StarButton.js

This introduces the possibility to expand the player controls, and as a first step, it adds a "star song" action as per https://github.com/deluan/navidrome/issues/287#issuecomment-674239809

Player toolbar

---

go.mod
go.sum
server/middlewares.go
server/server.go

Add HTTP security headers

---

ui/package-lock.json
ui/package.json
ui/src/audioplayer/Player.js

Only link from current playing song title to album view if not in iOS

---

Makefile
db/migration/20201010162350_add_album_size.go
model/album.go
persistence/album_repository.go
ui/src/album/AlbumDetails.js
ui/src/album/AlbumListView.js

add size to album details

---

ui/src/album/AlbumDetails.js
ui/src/album/AlbumGridView.js
ui/src/album/styles.js
ui/src/common/PlayButton.js
ui/src/common/RangeField.js

Improve Album Grid

---

resources/i18n/ja.json

I translated the added text and changed "compilation" back to English from "コンピレーション".
It would appear as this screenshot.

Fix ja translation

---

.github/workflows/pipeline.yml

Upgrade pipeline to use docker/setup-buildx-action

---

resources/i18n/fr.json

Opening this PR to update the new keys pending translation.  
This also fixes a few mistakes in some words.

Update French translation

---

ui/src/dialogs/AddToPlaylistDialog.js
ui/src/dialogs/SelectPlaylistInput.js

Mobile View Select a Playlist Input width fix

SelectPlaylist Input mobile view fix

---

Makefile
go.mod

This is a follow-up to the discussion I had with @deluan [on Discord](https://discord.com/channels/671335427726114836/704303730660737113/819228755918716988).

Increase go version requirement to 1.16

---

conf/configuration.go
model/mediafile.go
persistence/album_repository.go
scanner/mapping.go
server/subsonic/filter/filters.go
ui/src/album/albumLists.js

Add option to sort Recently Added by file's mtime instead of time of import

---

ui/src/themes/index.js
ui/src/themes/spotify.js

Related to [issue](https://github.com/navidrome/navidrome/issues/816)
**Screenshots**
Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>
@deluan 
Requesting review

style: New Theme Added - Spotify

---

resources/i18n/zh-Hans.json

Improve the simplified Chinese translation accuracy and fix the parts that are not translated.

Update Simplified Chinese translation

---

ui/package-lock.json
ui/package.json
ui/src/audioplayer/Player.js
ui/src/consts.js
ui/src/layout/Layout.js
ui/src/personal/Personal.js
ui/src/themes/useCurrentTheme.js
ui/src/themes/useCurrentTheme.test.js

This PR adds an `Auto` theme preference option in the Personal settings that would set the theme of the site according to the browser/OS preference.
Fixes #260

Fix #260: Add `Auto` theme preference to set theme automatically.

---

resources/i18n/es.json
resources/i18n/fr.json

Here are the translations for both languages. 
9fb55d40 does some reformatting on top of adding new fields, so I'm hoping I didn't miss any new translations. 
I've also raised [an issue on discord](https://discord.com/channels/671335427726114836/818940805494341683/823487712924270633) concerning a test failing when pushing. Since this also happens on a clean repo on the `master` branch I've decided to push using the `--no-verify` tag. Let me know if this is a concern.

Update translations for French and Spanish

---

CONTRIBUTING.md

Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>
Closes issue #827 
Created a contributing.md file that contains the contributing guidelines

docs(contributing.md): Contributing guidelines added - I827

---

server/subsonic/helpers.go

Add `/` to `_` mapping for song tags so that it becomes playable in subsonic clients.
Fix #592.

Add `/` to `_` mapping for file tags.

---

ui/src/artist/ArtistList.js

This closes #925. Will test it myself but wanted to push so others could try it too

remove syncWithLocation prop from ArtistList

---

ui/src/themes/dark.js
ui/src/themes/spotify.js

Follow up from https://github.com/navidrome/navidrome/pull/940

[Theme] Fix login page UI contrast in dark,spotify

---

ui/src/album/AlbumDetails.js
ui/src/album/AlbumGridView.js
ui/src/album/AlbumShow.js
ui/src/audioplayer/Player.js
ui/src/playlist/PlaylistDetails.js
ui/src/playlist/PlaylistShow.js
ui/src/themes/green.js
ui/src/themes/index.js
ui/src/themes/spotify.js

I've introduced some possible overrides like `NDAlbumGridView`, `NDAlbumDetails` etc. to make theming much more flexible.
I'm trying to modify the player as well, but overriding audioTitle (from below), after assigning a class doesn't seem to work.
https://github.com/navidrome/navidrome/blob/01ba00ccdd3b98248ffef8bfb59bdc43a873d693/ui/src/audioplayer/Player.js#L24-L35

Make spotify-ish more spotify-ish

---

ui/src/album/AlbumListView.js
ui/src/common/SongDetails.js

Fixes https://github.com/navidrome/navidrome/issues/910
Before:
Now:

Album details UI fix

---

ui/src/common/SongDatagrid.js

Closes #943 issue of the header row being visually too similar to the song rows.
Description: Improves visual distinction of the the header row for table for readability.
Changes: The Header Cell titles have all been set to bold and the Header Row is now distinctly more spaced out to improve visibility.

style(SongDataGrid): Improved Header Readability - #943

---

ui/src/playlist/PlaylistActions.js
ui/src/playlist/PlaylistShow.js
ui/src/playlist/PlaylistSongs.js

Fixes #621 
I've added pagination in the playlist. Drag and drop also work well. 
Requesting review @deluan

 Pagination added in playlist

---

ui/src/common/SongDatagrid.js

The broken Song Context Menu due to the changes has now been fixed.

style(SongDataGrid): Improved Header Readability for Songs List

---

server/app/serve_index.go

#1004 
Replaced a numerical literal with a constant from net/http

refactor(server/app/serve_index.go): replaced literal 302 with http constant - #1004

---

Makefile
ui/src/layout/Login.js

Fixing welcome message styles/1014

---

db/migration/20210418232815_fix_album_comments.go
persistence/album_repository.go
persistence/album_repository_test.go
ui/src/album/AlbumShow.js
ui/src/album/AlbumSongs.js
ui/src/album/AlbumSongs.test.js

Based on conversation on #963.

Better handling of album comments

---

ui/src/themes/spotify.js

Fixes https://github.com/navidrome/navidrome/issues/1066

[Spotify-ish] Indicate active page number

---

ui/src/themes/spotify.js

Fixes https://github.com/navidrome/navidrome/issues/1089

Spotify-ish: Account screen width in title truncating

---

ui/package-lock.json
ui/package.json
ui/src/dialogs/AddToPlaylistDialog.test.js
ui/src/dialogs/SelectPlaylistInput.test.js

This PR does the following:
- FIxes JS tests in _AddToPlaylistDialog.test.js_ .
- Remove `jest-environment-jsdom-sixteen` since jsdom is now up-to-date.
- Minor refactor in _SelectPlaylistInput.test.js_.
Resolves the first check item in #1105.

Fix JS tests and remove unwanted dependency.

---

ui/src/themes/ligera.js

Fixes [error](https://github.com/navidrome/navidrome/pull/1083#issuecomment-839320614).

Fix Ligera Error

---

persistence/user_repository.go
persistence/user_repository_test.go
tests/mock_persistence.go
tests/mock_user_repo.go
ui/src/i18n/en.json
ui/src/user/DeleteUserButton.js
ui/src/user/UserCreate.js
ui/src/user/UserEdit.js

This adds more descriptive success notifications in the UI when a user is Created/Edited/Deleted. Currently it just says "Element was [..]".
It also adds validation in the backend to ensure that a username is unique. Currently when attempting to create or edit a user to have a username that already exists the server just returns an error (due to the unique constraint in the DB).

User management improvements

---

.github/workflows/pipeline.yml
ui/package-lock.json
ui/package.json
ui/public/index.html
ui/src/album/albumLists.js
ui/src/audioplayer/Player.js
ui/src/dialogs/AddToPlaylistDialog.test.js
ui/src/dialogs/SelectPlaylistInput.test.js
ui/src/i18n/useGetLanguageChoices.js
ui/src/index.js
ui/src/layout/Layout.js
ui/src/layout/Logout.js
ui/src/routes.js
ui/src/store/createAdminStore.js
ui/src/themes/useCurrentTheme.js

Upgrade Web UI to Create-React-App 4 and React 17

---

ui/src/album/AlbumList.js

Probable solution to albumList toggling - lag issue

---

cmd/root.go
conf/configuration.go
consts/consts.go
server/app/app.go
server/app/app_suite_test.go
server/app/playlists.go
server/auth.go
server/auth_test.go
server/serve_index.go
server/serve_index_test.go
server/server.go
server/server_suite_test.go
server/subsonic/api.go
ui/src/authProvider.js
ui/src/consts.js
ui/src/eventStream.js

BREAKING CHANGE!
This is a preparation for allowing plugins to add new endpoints to Navidrome. As a result, the Native API routes were changed:
```
/app/login => /auth/login
/app/createAdmin => /auth/createAdmin
/app/api/* => /api/*
```
---
Hey @ajgon , I did some refactoring in the http routing code, and also changed a bit the code you contributed in #1152 
I don't have the setup required to test if the reverse proxy authentication is still working correctly. Can you please try this branch and let me know? Thanks!

Refactor routing

---

ui/src/song/SongList.js

Genre and Comments columns in Songs listview (hidden by default)

Genre and Comments columns in Songs listview

---

.github/workflows/pipeline.yml
.gitignore
Makefile

Add git version info to release source archive

---

.github/workflows/pipeline.dockerfile
.github/workflows/pipeline.yml

Build and release Docker image for Linux 32 bit platform

---

ui/package.json
ui/src/album/AlbumActions.js

added a dependency npm was complaining about
added playlist to album actions

add to playlist on albumlist actions

---

scanner/playlist_sync.go
scanner/playlist_sync_test.go
tests/fixtures/playlists/pls1.m3u

Support local paths as urls in playlists. Fixes #1215

---

resources/i18n/fr.json

Hello, I noticed some grammar mistakes and decided to offer a correction.

Correct some french translations

---

conf/configuration.go
conf/defaults.go
conf/defaults_win.go
consts/consts.go
scanner/metadata/metadata.go
scanner/metadata/taglib/get_filename.go
scanner/metadata/taglib/get_filename_win.go
scanner/metadata/taglib/taglib_wrapper.cpp
scanner/metadata/taglib/taglib_wrapper.go
scanner/metadata/taglib/taglib_wrapper.h

Use wchar_t for tagLib filenames on Windows

---

resources/i18n/ru.json

ru.json update

---

ui/src/themes/ligera.js
ui/src/themes/spotify.js

Fixes the following scroll issue in spotify and ligara
https://user-images.githubusercontent.com/2987087/132694515-22ab7537-adb4-45d7-b4c2-92e4ec892bb9.mov
https://user-images.githubusercontent.com/2987087/132694565-cb4a4a8f-49c0-413c-a2e3-c0b8161f57af.mov

Fix sidebar scroll height

---

conf/configuration.go
server/serve_index.go
server/serve_index_test.go
ui/src/App.js
ui/src/config.js
ui/src/dialogs/AddToPlaylistDialog.js
ui/src/i18n/en.json
ui/src/layout/Menu.js
ui/src/layout/PlaylistsSubMenu.js
ui/src/layout/SubMenu.js
ui/src/playlist/PlaylistCreate.js

Based on work by @aldrinjenson. Closes #771, supersedes #941

Move Playlists to the sidebar menu

---

ui/package-lock.json
ui/package.json

Bump react-jinke-music-player from 4.24.0 to 4.24.2

---

ui/src/artist/ArtistShow.js

This is a follow-up PR for handling any or existing issues on the Artist Details page; first fix for "Unknown artist," heading alignment, as in the image below, there is a misalignment of Artist Name, which is fixed in this PR
Feedbacks are most welcomed. Thank you!

Fix unknown artist err

---

model/criteria/operators.go

Combined multiple appends into a single one

---

cmd/root.go
conf/configuration.go
core/agents/listenbrainz/agent.go
server/serve_index.go
server/serve_index_test.go
ui/src/config.js
ui/src/personal/Personal.js
ui/src/player/PlayerEdit.js

Enables ListenBrainz and changes config to `ListenBrainz.Enabled`

Rename ListenBrainz config flag and enable by default

---

bg.json

feat: Added Bulgarian Language Translation
`navidrome/resources/i18n/bg.json`
Initial Release

Added Bulgarian Translation

---

conf/configuration.go
core/agents/listenbrainz/agent.go
core/agents/listenbrainz/agent_test.go
core/agents/listenbrainz/auth_router.go
core/agents/listenbrainz/auth_router_test.go
core/agents/listenbrainz/client.go
core/agents/listenbrainz/client_test.go
server/initial_setup.go

- ListenBrainz.BaseURL config value

feat: Add listenbrainz base url configuration

---

ui/src/artist/DesktopArtistDetails.js

This PR fixes the Add to Playlist dialog not showing up on the Artist details page.
Fixes: #1656 
Thank you!

[FIX] Add to Playlist Dialog on Artist Page

---

ui/src/themes/electricPurple.css.js
ui/src/themes/electricPurple.js
ui/src/themes/index.js

Add theme import theme Electric Purple

Add theme import theme Electric Purple

---

ui/src/themes/nord.js

Nord theme fix - give links a different colour to regular text

---

ui/src/utils/formatters.js
ui/src/utils/formatters.test.js

Fix bug in duration format logic

---

ui/src/themes/gruvboxDark.css.js
ui/src/themes/gruvboxDark.js
ui/src/themes/index.js

Adds a Gruvbox Dark color theme. Successfully built and tested

Add Gruvbox Dark color theme

---

ui/src/personal/ReplayGainToggle.js

fix order of gain menu options

---

ui/src/index.css

This PR takes the changes from #1987 and just puts it in `index.css`

fixes the slide bar clickable

---

ui/src/SharePlayer.js

Limit width of share player

---

resources/i18n/zh-Hans.json

updated translations for Chinese.

Update Chinese translations

---

resources/i18n/ar.json

Add Arabic translation

---

ui/src/App.js
ui/src/personal/SelectLanguage.js

Fixed issue no #2174

---

conf/configuration.go
persistence/mediafile_repository.go
persistence/sql_base_repository.go
persistence/sql_search.go

This should make Symfonium syncs faster on large libraries
c/c @Tolriq

Optimize pagination, removing offset

---

persistence/sql_annotations.go

Fix findMatchingTrack prioritizing irrelevant annotations (better getTopSongs results)

---

server/subsonic/opensubsonic.go

https://github.com/opensubsonic/open-subsonic-api/pull/74

Support for form post extension (OpenSubsonic)

---

server/subsonic/helpers.go
server/subsonic/helpers_test.go
server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .JSON
server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 with data should match .XML
server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 without data should match .JSON
server/subsonic/responses/.snapshots/Responses AlbumWithSongsID3 without data should match .XML
server/subsonic/responses/responses.go
server/subsonic/responses/responses_test.go

Ref: https://github.com/opensubsonic/open-subsonic-api/pull/80

Exposes OpenSubsonic's `originalReleaseDate`.

---

.github/workflows/pipeline.yml
Makefile
core/ffmpeg/ffmpeg.go
core/playback/mpv/mpv.go
core/playback/mpv/track.go
scanner/metadata/ffmpeg/ffmpeg.go
scanner/metadata/metadata.go
scanner/metadata/taglib/taglib.go
scanner/metadata/taglib/taglib_test.go
scanner/metadata/taglib/taglib_wrapper.cpp
scanner/metadata/taglib/taglib_wrapper.go
scanner/metadata/taglib/taglib_wrapper.h
scanner/tag_scanner.go
tests/mock_ffmpeg.go
utils/files.go

Upgrade to TagLib 2

---

conf/configuration.go
core/playback/mpv/mpv.go
core/playback/mpv/track.go

Solves https://github.com/navidrome/navidrome/discussions/2875
Useful for e.g., snapcast integration

externalize MPVTemplate

---

core/external_metadata.go
persistence/album_repository.go
persistence/mediafile_repository.go
persistence/playlist_track_repository.go
persistence/radio_repository.go
scanner/mapping.go
scanner/mapping_internal_test.go
utils/strings.go
utils/strings_test.go

Make sorting lists by name/title case-insensitive

---

ui/src/themes/catppuccinMacchiato.css.js
ui/src/themes/catppuccinMacchiato.js
ui/src/themes/index.js

Catppuccin Macchiato theme for Navidrome, let me know if you see a need for any adjustments

Add Catppuccin Macchiato Theme

---

server/subsonic/responses/.snapshots/Responses LyricsList with data should match .XML
server/subsonic/responses/responses.go

Fix XML marshaling of OpenSubsonic structured lyrics

---

ui/src/themes/index.js
ui/src/themes/nuclear.css.js
ui/src/themes/nuclear.js

Like Gruvbox, but darker and more green.

Add Nuclear Theme

---

ui/src/playlist/PlaylistEdit.js
ui/src/playlist/PlaylistList.js

Auto import toggle for playlist list

---

ui/src/reducers/replayGainReducer.js

Resolves #2933. To prevent this from happening again, make the localstorage keys consts for set/get

[bugfix]: use same key for replaygain

---

ui/src/common/ContextMenus.js
ui/src/common/SongDatagrid.js

fix(common): Hide Share/Get Info items in disc context menu - #3204

---

resources/i18n/hu.json
ui/src/i18n/en.json

For the Hungarian patch you can find the changes here in detail: https://pastebin.com/GLtmwELv

Hungarian patch and typo fix for English

---

conf/configuration.go
server/public/encode_id.go
server/public/public.go
server/public/public_test.go
server/serve_index.go
ui/src/config.js
ui/src/dialogs/ShareDialog.js
ui/src/share/ShareEdit.js
ui/src/share/ShareList.js
ui/src/share/SharePlayer.js
ui/src/utils/urls.js

Add ShareURL configuration option 

---

persistence/album_repository.go
persistence/artist_repository.go
persistence/mediafile_repository.go

Fix Genre and ID filters

---

resources/i18n/sr.json

Here is the UI translation to Serbian.

Add Serbian translation

---

persistence/mediafile_repository.go
persistence/player_repository.go
persistence/playlist_repository.go
persistence/share_repository.go

This fixes some of the columns that weren't sortable after the new  release.

fix(ui): sort mappings

---

ui/src/audioplayer/AudioTitle.js
ui/src/audioplayer/Player.js
ui/src/common/QualityInfo.js
ui/src/common/QualityInfo.test.js
ui/src/utils/calculateReplayGain.js

show effective db of track when playing

---

scanner/scanner.go
scanner/tag_scanner.go

fix(scanner): stop re-reading files that were recently imported.

---

ui/src/actions/player.js
ui/src/audioplayer/Player.js
ui/src/reducers/playerReducer.js
ui/src/share/SharePlayer.js
ui/src/store/createAdminStore.js

fix(ui): save play mode for player - 3019

---

server/auth.go
server/auth_test.go

This PR makes enabling reverse proxy authentication explicit also when navidrome listens on a unix socket.
The rationale is that standard authentication means should also work when listening on a unix socket, and implicitly enabling it can be dangerous for unsuspecting users.
This also solves the error spamming issue reported in #3046.
To enable reverse proxy authentication when listening on a unix socket, the special value `@` must be used instead of an IP range in the `ReverseProxyWhitelist` option. This was chosen instead of e.g. `unix` or `0.0.0.0/0` because it matches the IP address displayed in the warning:
> WARN[0004] IP is not whitelisted for reverse proxy login  client-ip=@ proxy-ip=@ requestId=...
but I'm open to changing this.
If this PR is accepted, I will also update the …

Require explicitly enabling reverse proxy auth for unix sockets

---

ui/package-lock.json
ui/package.json
ui/vite.config.js

- vite: use rollup/wasm-node
- use vitejs/plugin-react instead of plugin-react-swc
closes #3390

Fix build on FreeBSD

---

resources/i18n/sr.json

Here is an update of the Serbian translation.

feat(ui): Update Serbian translation

---

core/playlists.go
core/playlists_test.go

fix(playlists): make the m3u parser case-insensitive again

---

db/migrations/20241024125533_fix_sort_tags_collation_and_index.sql
model/album.go
model/mediafile.go
model/mediafile_test.go
persistence/album_repository.go
persistence/artist_repository.go
persistence/artist_repository_test.go
persistence/collation_test.go
persistence/helpers.go
persistence/helpers_test.go
persistence/mediafile_repository.go
persistence/player_repository.go
persistence/playlist_repository.go
persistence/playlist_track_repository.go
persistence/radio_repository.go
persistence/share_repository.go
persistence/sql_base_repository.go
scanner/playlist_importer_test.go

fix(server): fix case-insensitive sort order and add indexes to improve performance

---

resources/i18n/eu.json

Added:
- lastAccessAt
Updated:
- lastLoginAt
- logout

fix(ui): update eu.json

---

cmd/backup.go

Fix typo in backup prune message

---

ui/src/authProvider.js
ui/src/dataProvider/httpClient.js
ui/src/utils/removeHomeCache.js

Resolves #3613. Probably a better way (e.g., just don't cache it in the first place if unset), but this appears to work?

fix(ui): remove index.html from service worker cache after creating admin user

---

ui/src/album/AlbumList.jsx
ui/src/artist/ArtistList.jsx
ui/src/song/SongList.jsx

Cherry picked from #3677 (thanks @henrikno)

feat(ui): Allow filtering on multiple genres

---

core/artwork/reader_album.go

Fixes https://github.com/navidrome/navidrome/discussions/3676#discussioncomment-12007075

Fix local artist artwork

---

model/metadata/metadata_test.go
resources/mappings.yaml

fix lyrics and comments being truncated

---

ui/src/album/AlbumInfo.jsx
ui/src/common/ArtistLinkField.jsx
ui/src/common/SongInfo.jsx

Also makes info entries with newlines (lyrics) look nicer

feat(ui): Show performer subrole(s) where possible

---

core/playlists.go
core/playlists_test.go
tests/fixtures/playlists/pls1.m3u
tests/fixtures/playlists/subfolder2/pls2.m3u
tests/test_helpers.go
utils/slice/slice_test.go

fix(server): Import absolute paths in m3u

---

db/migrations/20241026183640_support_new_scanner.go

fix(server): db migration not working when MusicFolder is a relative path

---

ui/src/album/AlbumInfo.jsx
ui/src/album/AlbumList.jsx
ui/src/common/QuickFilter.jsx
ui/src/common/SongInfo.jsx
ui/src/dialogs/AboutDialog.jsx
ui/src/dialogs/HelpDialog.jsx
ui/src/layout/Menu.jsx
ui/vite.config.js

1. For some bizarre reason, importing inflection by itself is undefined. But you can import specific functions
2. Per https://github.com/vite-pwa/vite-plugin-pwa/issues/419, `type: 'module',` is only for non-chromium browsers

fix(ui): Fix `make dev`

---

resources/i18n/es.json

Corrected "aletorio" and added some more translations

fix(ui): update Español translation

---

db/migrations/20241026183640_support_new_scanner.go

fix(server): skip non-UTF encoded filenames during migration.

---

resources/i18n/eu.json

Update Basque localisation

---

resources/i18n/fr.json

Update french translation and reorder the file the same way as the en.json template, making comparison easier.

fix(ui): Update Français, reorder translation according to en.json template

---

resources/i18n/it.json

translations from ENG version to ITA

---

ui/src/common/SongInfo.jsx
ui/src/i18n/en.json

Resolves https://github.com/navidrome/navidrome/discussions/3955

feat(ui): show sampleRate in song info dialog

---

resources/i18n/no.json

Started from scratch with original English json and translated everything to Norwegian. Opted to keep certain English words like "Shuffle" as these are more commonly used these days than their antiquated and clunky Norwegian counterparts.

fix(ui): update Norwegian translation

---

resources/i18n/zh-Hans.json

- Complete the translation of all entries
- Change the translation of **genre** from _类型_ to _流派_ to avoid confusion with **media** and **releaseType**
- Adjust the entries‘ order to align with _en.json_ for easier comparison in future translations

fix(ui): update Chinese (Simplified) translations

---

resources/i18n/ca.json

Added missing lines on the i18n/ca.json file.

Updated catalan translations

---

resources/i18n/sr.json

Here is an update of the Serbian translation.

fix(ui): update Serbian translations

---

conf/configuration.go
core/share.go
ui/src/index.css

feat(server): add DefaultShareExpiration config option

---

server/subsonic/filter/filters.go
server/subsonic/media_retrieval.go

Use `albumartists` or `artists`

find artist by multivalued exact match, instead of 'artist' field

---

model/metadata/map_participants_test.go

- expand PERFORMER tests in map_participants_test.go
- add checks for `MUSICBRAINZ_PERFORMERID` handling
- `make test`

Add PERFORMER tests

---

resources/i18n/hu.json

added: bitDepth, sampleRate, album/date, saveQueue, missing/empty, actions/remove_all, remove_all_missing_title, remove_all_missing_content, scanType, status, elapsedTime
edited (better sentence structuring, making it make more sense, etc.): listenBrainzLinkSuccess, playListsText

[HU translation] added new strings

---

ui/src/playlist/PlaylistDetails.jsx
ui/src/subsonic/index.js
ui/src/subsonic/index.test.js

Adds playlist cover art display to the `PlaylistShow` view, similar to how album covers are displayed in the `AlbumShow` view. This implements a complete playlist image viewing experience with lightbox functionality and proper error handling.
- **🖼️ Playlist Cover Art Display**: Shows dynamically generated playlist covers or placeholders
- **🔍 Lightbox Integration**: Click to view full-size playlist images with the same experience as albums
- **⚡ Smooth Transitions**: Loading states with opacity transitions for better UX
- **🔄 Smart Cache Busting**: Prevents stale images when switching between playlists
- **🛡️ Error Handling**: Graceful fallback for failed image loads and empty playlists
- **📱 Responsive Design**: Adapts to different screen sizes with proper scaling …

feat(ui): Add playlist cover art display

---

resources/i18n/hu.json

new Hungarian strings

---

resources/i18n/pt-br.json
ui/src/dialogs/AddToPlaylistDialog.test.jsx
ui/src/dialogs/SelectPlaylistInput.jsx
ui/src/dialogs/SelectPlaylistInput.test.jsx
ui/src/i18n/en.json

This PR fixes the SelectPlaylistInput dropdown overlay issue and significantly improves code maintainability through component refactoring.
- **Fixed dropdown overlay**: Replaced Material-UI Autocomplete with fixed list to prevent action buttons below from being unclickable
- **Fixed list container**: Added 200px height with scroll for consistent layout
Broke down the monolithic component into 7 smaller, focused components:
- **PlaylistSearchField**: Search input with add button
- **EmptyPlaylistMessage**: Empty states with context-aware messages
- **PlaylistListItem**: Individual playlist items with checkboxes
- **CreatePlaylistItem**: Create new playlist option in list
- **PlaylistList**: Container with conditional rendering logic
- **SelectedPlaylistChip**: Selected playlist chips with …

Fix SelectPlaylistInput layout and improve maintainability

---

conf/configuration.go
server/nativeapi/config.go
server/nativeapi/config_test.go
ui/src/dialogs/AboutDialog.jsx
ui/src/dialogs/aboutUtils.js
ui/src/dialogs/aboutUtils.test.js

This PR simplifies the configuration endpoint (`/config`) by replacing reflection-based field extraction with JSON marshaling/unmarshaling, resulting in cleaner code.
- **Configuration Structure (`conf/configuration.go`)**:
- Added `json:",omitzero"` tags to optional nested structs to exclude empty structs from JSON output
- Added `json:",omitempty"` tags to optional fields to exclude empty values
- Moved `LyricsPriority` field to be grouped with other priority fields for better organization
- **Config Endpoint (`server/nativeapi/config.go`)**:
- Replaced reflection-based field flattening with JSON marshaling approach
- Simplified response structure: now returns nested configuration map instead of flat key-value pairs
- Removed `configEntry` struct and associated reflection code
- …

refactor(config): simplify configuration endpoint with JSON serialization

---

Dockerfile

improved wording and consistency in code:
orignal - original

minor text cleanup

---

model/searchable.go
persistence/album_repository.go
persistence/artist_repository.go
persistence/artist_repository_test.go
persistence/mediafile_repository.go
persistence/mediafile_repository_test.go
persistence/sql_search.go
server/subsonic/searching.go
tests/mock_album_repo.go
tests/mock_artist_repo.go
tests/mock_mediafile_repo.go

This PR simplifies the search API and optimizes search performance, particularly for OpenSubsonic compatibility where empty search queries need efficient natural ordering.
1. **API Simplification**: Removed the unused `includeMissing` parameter from all search methods across repositories (albums, artists, media files). This parameter was always passed as `false`, so removing it reduces code complexity.
2. **Performance Optimization**: Introduced configurable natural ordering for search operations:
- For **artists**: Changed from `rowid` to `id` ordering, which is more performant due to GROUP BY clauses in artist queries
- For **albums/media files**: Maintained `rowid` ordering for optimal performance
- Added documentation explaining the purpose of natural ordering for OpenSubsonic empty …

Refactor search API and optimize performance for OpenSubsonic compatibility
